In [62]:
import numpy as np
import matplotlib.pyplot as plt
from scipy import optimize
from scipy.optimize import minimize
from helper import *
import pandas as pd

In [2]:
mu_sun= 1.327e11 ## km^3/s^2  
mu_earth= 3.986e5 ## km^3/s^2  # 3.986e5
mu_mars= 4.2830e4 ## km^3/s^2
mu_venus = 32.4776e4

mu_moon = 0.4902e4 ## km^3/s^2 Not given in paper

SOI_earth = 923502.24 # km
SOI_mars = 577723.87 # km 577723.87 
SOI_moon = 66300

D_mars = 2.279e8
D_earth = 1.496e8
D_venus = 1.0815e8
D_moon = 384400 # km

r_LEO = 463
R_LEO = 6378.2 + r_LEO

w_earth = 1.99177621e-7 # rad/s
w_mars = 1.05850987e-7 # rad/s
w_venus = 3.23861161e-7
w_moon = 2.6653e-6 # rad/s

r_LMO = 200
R_LMO = 3397.0 + r_LMO

In [3]:
def earth_mars_hohmann_transfer(result_str = False):
    mu_sun= 1.327e11 ## km^3/s^2
    mu_earth= 3.986e5 ## km^3/s^2
    mu_mars= 4.2830e4 ## km^3/s^2

    SOI_earth = 923502.24 # km
    SOI_mars = 577723.87 # km

    
    r_mars = 2.279e8
    r_earth = 1.496e8

    r_LEO = 463
    R_LEO = 6378.2 + r_LEO

    r_LMO = 200
    R_LMO = 3397.0 + r_LMO

    a_transfer = (r_mars + r_earth)/2


    delta_v1 = np.sqrt(mu_sun/r_earth) * (np.sqrt((2*r_mars)/(r_earth+r_mars)) - 1)

    delta_v2 = np.sqrt(mu_sun/r_mars) * (1 - np.sqrt((2*r_earth)/(r_earth+r_mars)))

    v_p = np.sqrt((delta_v1)**2 + ((2*mu_earth)/R_LEO))

    v_c = np.sqrt(mu_earth/R_LEO)
    delta_v_Earth = v_p - v_c
    delta_v_inf = np.sqrt(mu_sun/r_mars)*(1 - np.sqrt((2*r_earth)/(r_earth + r_mars)))
    delta_v_mars = np.sqrt(delta_v_inf**2 + (2*mu_mars/R_LMO)) - np.sqrt(mu_mars*(1)/R_LMO)

    delta_v_total = delta_v_Earth + delta_v_mars


    t_of_f = np.pi * np.sqrt(((r_mars + r_earth)**3)/(8*mu_sun))
    t_of_f_days = t_of_f/(60*60*24)

    
    

    if result_str:
        print(f"""
Delta V_Leo = {delta_v_Earth}
Delta V_LMO = {delta_v_mars}
Delta V_Total = {delta_v_total}

Time of Flight = {t_of_f_days:.2f} Days
Semi-major axis = {a_transfer:e} Km
""")

    return delta_v_total

earth_mars_hohmann_transfer(result_str= True)

Delta V_Leo = 3.5558147563670417
Delta V_LMO = 2.101362221346033
Delta V_Total = 5.657176977713075

Time of Flight = 258.84 Days
Semi-major axis = 1.887500e+08 Km

np.float64(5.657176977713075)

In [53]:
def lambert_solve(R1,R2,t,mu, trajectory_type, debug = False):
    # t in days
    t = t* (60*60*24) # convert to seconds


    r1 = np.linalg.norm(R1) # Mag of R1
    r2 = np.linalg.norm(R2) # Mag of R2

    cross_r1_r2 = np.cross(R1,R2) # cross product if R1 and R2

    if trajectory_type == "pro": # (3.23)
        if cross_r1_r2[2] >= 0:
            theta = np.arccos(np.dot(R1,R2)/(r1*r2))
        
        else:
            theta = 2*np.pi - np.arccos(np.dot(R1,R2)/(r1*r2))

    elif trajectory_type == "retro": # (3.24)
        if cross_r1_r2[2] < 0:
            theta = np.arccos(np.dot(R1,R2)/(r1*r2))
        
        else:
            theta = 2*np.pi - np.arccos(np.dot(R1,R2)/(r1*r2))

    else:
        print("Trajectory type not specified")
        return

    # print(np.rad2deg(theta))
    # if np.rad2deg(theta) == 180.0:
    #     print("180deg anomaly => Hohmann Transfer")
    #     print(f"{earth_mars_hohmann_transfer()}")
    #     return earth_mars_hohmann_transfer() 
    A = np.sin(theta) * np.sqrt((r1*r2) / (1-np.cos(theta))) # (3.25)

    ## Determine where approximately F(z) changes sign. This will be used as an initial guess for root-finding.
    z = -100
    while F(z,t,r1,r2,mu,A) < 0:
        z = z + 0.1


    ## Error Tolerance and max number of iterations


    # Apply Newton-Raphson root-finder from scipy library
    z = optimize.newton(F,z, args = (t,r1,r2,mu,A)) 
    print(z)

    # Lagrange Coefficients
    f = 1 - (y(z,r1,r2,A)/r1) # (3.31)
    g = A*np.sqrt(y(z,r1,r2,A)/mu) # (3.32)

    
    fdot = (np.sqrt(mu)/(r1*r2)) * (np.sqrt(y(z,r1,r2,A)/stumpC(z)) * (z*stumpS(z) -1)) # (3.33)
    gdot = 1 - (y(z,r1,r2,A)/r2) # (3.34)
    
    if debug:
        print(f"{g = } {R2 = } {f = } {R1 = }")
    V1 = (1/g)*(R2 - f*R1) # (3.35)
    
    V2 = (1/g)*(gdot*R2 - R1) # (3.36)

    if debug:
        print(f"{r1 = }\t{r2 = }\t{cross_r1_r2 = }\t{A = } \n {V1 = }\t{V2 = }")

    return V1, V2


mu_sun = 1.327e11  # Suns gravitational parameter in (km^3/s^2) 

R1 = np.array([1.4762e+08 ,0.0000e+00 ,0.0000e+00])
R2 = np.array([-2.2800000e+08 , 2.7921947e-08 , 0.0000000e+00])
t_of_f = 60*60*24 * 270
lambert_solve(R1,R2, t_of_f, mu_sun, "pro", debug = True)

38.7769660198383
g = np.float64(8.452297419925728e-10) R2 = array([-2.2800000e+08,  2.7921947e-08,  0.0000000e+00]) f = np.float64(-1.544506164476358) R1 = array([1.4762e+08, 0.0000e+00, 0.0000e+00])
r1 = np.float64(147620000.0)	r2 = np.float64(228000000.0)	cross_r1_r2 = array([ 0.        , -0.        ,  4.12183782])	A = np.float64(1.588677986858443e-08)
 V1 = array([-35.2594341 ,  33.03474264,   0.        ])	V2 = array([  0.        , -21.38854697,  -0.        ])

(array([-35.2594341 ,  33.03474264,   0.        ]),
 array([  0.        , -21.38854697,  -0.        ]))

In [166]:
def simulate(anomaly, t_of_f): # t_of_f in degrees
    if anomaly == 180:
        return earth_mars_hohmann_transfer()
    R_earth = 1.4960e8 # km, average distance from sun
    h_earth = np.sqrt(R_earth * mu_sun) # circular orbit
    earth_orbit = Orbit(h_earth,0,0,0,0,0) # circular orbit

    R1, V1 = calculate_state_vector_from_orbit(earth_orbit,mu_sun,debug= False)

    R_mars = 2.279e8 # km, average distance from sun
    h_mars = np.sqrt(R_mars * mu_sun)
    mars_orbit = Orbit(h_mars,0,0,0,0,anomaly) # Weird Vd calculated at 180 deg. 
    print(anomaly)
    R2, V2 = calculate_state_vector_from_orbit(mars_orbit,mu_sun,debug=False)
    # print(f"{R2} {V2}")

    Vd, Va = lambert_solve(np.array(R1),np.array(R2),t_of_f,mu_sun,"pro", debug = False)
    print(f"{Vd = } {Va = }")
    v_inf_d = Vd - V1
    v_inf_a = Va - V2
    print(f"{v_inf_d = } {v_inf_a = }")

    r_LEO = 6378.2 + 463
    v_inf_d_mag = np.linalg.norm(v_inf_d)
    v_periapse = np.sqrt((v_inf_d_mag**2) + (2*mu_earth/r_LEO))
    v_o = np.sqrt(mu_earth/r_LEO)
    delta_v1 = v_periapse - v_o

    r_LMO = 3397 + 200
    v_inf_a_mag = np.linalg.norm(v_inf_a)
    v_periapse = np.sqrt((v_inf_a_mag**2) + (2*mu_mars/r_LMO))
    v_o = np.sqrt(mu_mars/r_LMO)

    delta_v2 = v_periapse - v_o
    delta_total = delta_v1 + delta_v2
    print(delta_v1, delta_v2, delta_total)
    return delta_v1, delta_v2, delta_total

## Given Anomaly

In [92]:
simulate(182,402)

14.019822029948564
Vd = array([ 7.31748344, 32.80464834, -0.        ]) Va = array([  8.26115987, -21.25853797,   0.        ])
v_inf_d = array([ 7.31748344,  3.02156446, -0.        ]) v_inf_a = array([7.41902342, 2.85709457, 0.        ])

(np.float64(5.753607938259554),
 np.float64(5.877734461865707),
 np.float64(11.631342400125261))

In [66]:
initial_guess = 300

def wrapped_simulate(x, anomaly):
    t_of_f = x
    deltaV_LEO, deltaV_LMO, delta_total = simulate(anomaly, t_of_f)
    return delta_total

optimized = minimize(wrapped_simulate,initial_guess, args = 185, method= "L-BFGS-B", bounds=[(200.0,400.0)])
print(f"\noptimized time = {optimized.x[0]} days")

[11.5825106]
Vd = array([ 2.03798596, 32.78666394, -0.        ]) Va = array([  4.39595505, -21.21970736,   0.        ])
v_inf_d = array([ 2.03798596,  3.00358006, -0.        ]) v_inf_a = array([2.29285804, 2.81880153, 0.        ])
[11.5825106]
Vd = array([ 2.03798596, 32.78666394, -0.        ]) Va = array([  4.39595505, -21.21970736,   0.        ])
v_inf_d = array([ 2.03798596,  3.00358006, -0.        ]) v_inf_a = array([2.29285804, 2.81880153, 0.        ])
[11.58136216]
Vd = array([ 2.0357583, 32.7866051, -0.       ]) Va = array([  4.39373162, -21.21986311,   0.        ])
v_inf_d = array([ 2.0357583 ,  3.00352122, -0.        ]) v_inf_a = array([2.29063461, 2.81864578, 0.        ])
[11.58136216]
Vd = array([ 2.0357583, 32.7866051, -0.       ]) Va = array([  4.39373162, -21.21986311,   0.        ])
v_inf_d = array([ 2.0357583 ,  3.00352122, -0.        ]) v_inf_a = array([2.29063461, 2.81864578, 0.        ])
[10.10460797]
Vd = array([-0.93496512, 32.70823562, -0.        ]) Va = array([  1.42865795, -21.427633  ,   0.        ])
v_inf_d = array([-0.93496512,  2.92515174, -0.        ]) v_inf_a = array([-0.67443906,  2.61087589,  0.        ])
[10.10460797]
Vd = array([-0.93496512, 32.70823562, -0.        ]) Va = array([  1.42865795, -21.427633  ,   0.        ])
v_inf_d = array([-0.93496512,  2.92515174, -0.        ]) v_inf_a = array([-0.67443906,  2.61087589,  0.        ])
[10.53148886]
Vd = array([-0.05426642, 32.73144943, -0.        ]) Va = array([  2.30768032, -21.36602492,   0.        ])
v_inf_d = array([-0.05426642,  2.94836555, -0.        ]) v_inf_a = array([0.2045833 , 2.67248397, 0.        ])
[10.53148886]
Vd = array([-0.05426642, 32.73144943, -0.        ]) Va = array([  2.30768032, -21.36602492,   0.        ])
v_inf_d = array([-0.05426642,  2.94836555, -0.        ]) v_inf_a = array([0.20458331, 2.67248397, 0.        ])
[10.41072663]
Vd = array([-0.30158629, 32.72492881, -0.        ]) Va = array([  2.06083108, -21.38332476,   0.        ])
v_inf_d = array([-0.30158629,  2.94184493, -0.        ]) v_inf_a = array([-0.04226593,  2.65518413,  0.        ])
[10.41072663]
Vd = array([-0.30158629, 32.72492881, -0.        ]) Va = array([  2.06083108, -21.38332476,   0.        ])
v_inf_d = array([-0.30158629,  2.94184493, -0.        ]) v_inf_a = array([-0.04226593,  2.65518413,  0.        ])
[10.39979232]
Vd = array([-0.32405059, 32.7243366 , -0.        ]) Va = array([  2.03840953, -21.38489616,   0.        ])
v_inf_d = array([-0.32405059,  2.94125272, -0.        ]) v_inf_a = array([-0.06468749,  2.65361273,  0.        ])
[10.39979232]
Vd = array([-0.32405059, 32.7243366 , -0.        ]) Va = array([  2.03840953, -21.38489616,   0.        ])
v_inf_d = array([-0.32405059,  2.94125272, -0.        ]) v_inf_a = array([-0.06468749,  2.65361273,  0.        ])
[10.40021188]
Vd = array([-0.32318839, 32.72435933, -0.        ]) Va = array([  2.03927009, -21.38483585,   0.        ])
v_inf_d = array([-0.32318839,  2.94127545, -0.        ]) v_inf_a = array([-0.06382692,  2.65367304,  0.        ])
[10.40021189]
Vd = array([-0.32318839, 32.72435933, -0.        ]) Va = array([  2.0392701 , -21.38483585,   0.        ])
v_inf_d = array([-0.32318839,  2.94127545, -0.        ]) v_inf_a = array([-0.06382692,  2.65367304,  0.        ])

optimized time = 265.5230064588461 days

In [ ]:
result = []

for anomaly in np.linspace(90,270,180):
    try:
        optimized = minimize(wrapped_simulate,initial_guess, args=anomaly, method = "Nelder-Mead", bounds=[(10,700)])
        result.append(anomaly)
        result.append(optimized.x[0])
    
    except:
        print(f"{anomaly} not valid")

[8.26921033]
Vd = array([20.59241939, 24.28136473,  0.        ]) Va = array([-15.93897395, -12.25002861,  -0.        ])
v_inf_d = array([20.59241939, -5.50171916,  0.        ]) v_inf_a = array([  8.19135814, -12.25002861,  -0.        ])
[8.62859145]
Vd = array([21.20008003, 24.00241866,  0.        ]) Va = array([-15.75586587, -12.95352724,  -0.        ])
v_inf_d = array([21.20008003, -5.78066522,  0.        ]) v_inf_a = array([  8.37446622, -12.95352724,  -0.        ])
[7.89187377]
Vd = array([19.93005437, 24.59059029,  0.        ]) Va = array([-16.14195835, -11.48142242,  -0.        ])
v_inf_d = array([19.93005437, -5.19249359,  0.        ]) v_inf_a = array([  7.98837374, -11.48142242,  -0.        ])
[7.49503845]
Vd = array([19.20485016, 24.93542556,  0.        ]) Va = array([-16.36831796, -10.63774257,  -0.        ])
v_inf_d = array([19.20485016, -4.84765833,  0.        ]) v_inf_a = array([  7.76201413, -10.63774257,  -0.        ])
[6.6358195]
Vd = array([17.52420497, 25.7603404 ,  0.        ]) Va = array([-16.90981538,  -8.67367994,  -0.        ])
v_inf_d = array([17.52420497, -4.02274348,  0.        ]) v_inf_a = array([ 7.22051671, -8.67367994, -0.        ])
[5.67546374]
Vd = array([15.44036686, 26.834695  ,  0.        ]) Va = array([-17.61505209,  -6.22072395,  -0.        ])
v_inf_d = array([15.44036686, -2.94838888,  0.        ]) v_inf_a = array([ 6.51528   , -6.22072395, -0.        ])
[3.37092239]
Vd = array([ 9.23954299, 30.38993239,  0.        ]) Va = array([-19.94881038,   1.20157902,   0.        ])
v_inf_d = array([9.23954299, 0.60684851, 0.        ]) v_inf_a = array([4.18152171, 1.20157902, 0.        ])
[0.43164858]
Vd = array([-3.32908279, 39.38315595,  0.        ]) Va = array([-25.85221645,  16.86002228,   0.        ])
v_inf_d = array([-3.32908279,  9.60007206,  0.        ]) v_inf_a = array([-1.72188436, 16.86002228,  0.        ])
[0.43164858]
Vd = array([-3.32908279, 39.38315595,  0.        ]) Va = array([-25.85221645,  16.86002228,   0.        ])
v_inf_d = array([-3.32908279,  9.60007206,  0.        ]) v_inf_a = array([-1.72188436, 16.86002228,  0.        ])
[4.59453238]
Vd = array([12.77816726, 28.29365333,  0.        ]) Va = array([-18.57275357,  -3.0572675 ,  -0.        ])
v_inf_d = array([12.77816726, -1.48943055,  0.        ]) v_inf_a = array([ 5.55757852, -3.0572675 , -0.        ])
[1.98416812]
Vd = array([ 4.26808852, 33.65252688,  0.        ]) Va = array([-22.0904696 ,   7.29396876,   0.        ])
v_inf_d = array([4.26808852, 3.869443  , 0.        ]) v_inf_a = array([2.03986249, 7.29396876, 0.        ])
[2.69886311]
Vd = array([ 6.98488898, 31.82268996,  0.        ]) Va = array([-20.88931294,   3.94848804,   0.        ])
v_inf_d = array([6.98488898, 2.03960608, 0.        ]) v_inf_a = array([3.24101915, 3.94848804, 0.        ])
[1.98416812]
Vd = array([ 4.26808852, 33.65252688,  0.        ]) Va = array([-22.0904696 ,   7.29396876,   0.        ])
v_inf_d = array([4.26808852, 3.869443  , 0.        ]) v_inf_a = array([2.03986249, 7.29396876, 0.        ])
[3.04014971]
Vd = array([ 8.16194621, 31.06511219,  0.        ]) Va = array([-20.39201748,   2.5111485 ,   0.        ])
v_inf_d = array([8.16194621, 1.28202831, 0.        ]) v_inf_a = array([3.73831461, 2.5111485 , 0.        ])
[2.34688953]
Vd = array([ 5.69314529, 32.67848283,  0.        ]) Va = array([-21.45107956,   5.53425798,   0.        ])
v_inf_d = array([5.69314529, 2.89539894, 0.        ]) v_inf_a = array([2.67925253, 5.53425798, 0.        ])
[2.87083363]
Vd = array([ 7.58673209, 31.43269774,  0.        ]) Va = array([-20.63331102,   3.21265463,   0.        ])
v_inf_d = array([7.58673209, 1.64961386, 0.        ]) v_inf_a = array([3.49702107, 3.21265463, 0.        ])
[2.52421911]
Vd = array([ 6.35442685, 32.23717085,  0.        ]) Va = array([-21.1613899,   4.7213541,   0.       ])
v_inf_d = array([6.35442685, 2.45408696, 0.        ]) v_inf_a = array([2.96894219, 4.7213541 , 0.        ])
[2.78518151]
Vd = array([ 7.28925892, 31.62476856,  0.        ]) Va = array([-20.75939174,   3.5761179 ,   0.        ])
v_inf_d = array([7.28925892, 1.84168468, 0.        ]) v_inf_a = array([3.37094035, 3.5761179 , 0.        ])
[2.87083363]
Vd = array([ 7.58673209, 31.43269774,  0.        ]) Va = array([-20.63331102,   3.21265463,   0.        ])
v_inf_d = array([7.58673209, 1.64961386, 0.        ]) v_inf_a = array([3.49702107, 3.21265463, 0.        ])
[2.74210574]
Vd = array([ 7.13795167, 31.72298158,  0.        ]) Va = array([-20.82386154,   3.76116837,   0.        ])
v_inf_d = array([7.13795167, 1.9398977 , 0.        ]) v_inf_a = array([3.30647055, 3.76116837, 0.        ])
[2.69886311]
Vd = array([ 6.98488898, 31.82268996,  0.        ]) Va = array([-20.88931294,   3.94848804,   0.        ])
v_inf_d = array([6.98488898, 2.03960608, 0.        ]) v_inf_a = array([3.24101915, 3.94848804, 0.        ])
[2.76366447]
Vd = array([ 7.21382274, 31.67369024,  0.        ]) Va = array([-20.79150531,   3.66836219,   0.        ])
v_inf_d = array([7.21382274, 1.89060635, 0.        ]) v_inf_a = array([3.33882678, 3.66836219, 0.        ])
[2.7205053]
Vd = array([ 7.06164175, 31.77264676,  0.        ]) Va = array([-20.85646316,   3.85454184,   0.        ])
v_inf_d = array([7.06164175, 1.98956287, 0.        ]) v_inf_a = array([3.27386893, 3.85454184, 0.        ])
[2.75289032]
Vd = array([ 7.17594181, 31.69828944,  0.        ]) Va = array([-20.80765292,   3.71469471,   0.        ])
v_inf_d = array([7.17594181, 1.91520556, 0.        ]) v_inf_a = array([3.32267917, 3.71469471, 0.        ])
[2.76366447]
Vd = array([ 7.21382274, 31.67369024,  0.        ]) Va = array([-20.79150531,   3.66836219,   0.        ])
v_inf_d = array([7.21382274, 1.89060635, 0.        ]) v_inf_a = array([3.33882678, 3.66836219, 0.        ])
[2.74749933]
Vd = array([ 7.15696043, 31.71062386,  0.        ]) Va = array([-20.81574958,   3.73791386,   0.        ])
v_inf_d = array([7.15696043, 1.92753998, 0.        ]) v_inf_a = array([3.31458251, 3.73791386, 0.        ])
[2.74210574]
Vd = array([ 7.13795167, 31.72298158,  0.        ]) Va = array([-20.82386154,   3.76116837,   0.        ])
v_inf_d = array([7.13795167, 1.9398977 , 0.        ]) v_inf_a = array([3.30647055, 3.76116837, 0.        ])
[2.75019515]
Vd = array([ 7.16645454, 31.70445375,  0.        ]) Va = array([-20.81169934,   3.72629987,   0.        ])
v_inf_d = array([7.16645454, 1.92136986, 0.        ]) v_inf_a = array([3.31863275, 3.72629987, 0.        ])
[2.74480286]
Vd = array([ 7.14745947, 31.71679981,  0.        ]) Va = array([-20.81980365,   3.74953669,   0.        ])
v_inf_d = array([7.14745947, 1.93371593, 0.        ]) v_inf_a = array([3.31052844, 3.74953669, 0.        ])
[2.74884732]
Vd = array([ 7.16170834, 31.70753808,  0.        ]) Va = array([-20.81372399,   3.73210576,   0.        ])
v_inf_d = array([7.16170834, 1.92445419, 0.        ]) v_inf_a = array([3.3166081 , 3.73210576, 0.        ])
[2.75019515]
Vd = array([ 7.16645454, 31.70445375,  0.        ]) Va = array([-20.81169934,   3.72629987,   0.        ])
v_inf_d = array([7.16645454, 1.92136986, 0.        ]) v_inf_a = array([3.31863275, 3.72629987, 0.        ])
[2.74817335]
Vd = array([ 7.15933459, 31.70908079,  0.        ]) Va = array([-20.81473667,   3.73500953,   0.        ])
v_inf_d = array([7.15933459, 1.92599691, 0.        ]) v_inf_a = array([3.31559542, 3.73500953, 0.        ])
[2.74952126]
Vd = array([ 7.16408165, 31.70599573,  0.        ]) Va = array([-20.81271155,   3.72920253,   0.        ])
v_inf_d = array([7.16408165, 1.92291185, 0.        ]) v_inf_a = array([3.31762054, 3.72920253, 0.        ])
[2.74851034]
Vd = array([ 7.16052152, 31.70830939,  0.        ]) Va = array([-20.8142303 ,   3.73355757,   0.        ])
v_inf_d = array([7.16052152, 1.92522551, 0.        ]) v_inf_a = array([3.31610179, 3.73355757, 0.        ])
[2.74918429]
Vd = array([ 7.16289505, 31.70676686,  0.        ]) Va = array([-20.81321774,   3.73065408,   0.        ])
v_inf_d = array([7.16289505, 1.92368298, 0.        ]) v_inf_a = array([3.31711435, 3.73065408, 0.        ])
[2.74867883]
Vd = array([ 7.16111494, 31.70792372,  0.        ]) Va = array([-20.81397713,   3.73283165,   0.        ])
v_inf_d = array([7.16111494, 1.92483984, 0.        ]) v_inf_a = array([3.31635496, 3.73283165, 0.        ])
[2.74901581]
Vd = array([ 7.1623017 , 31.70715246,  0.        ]) Va = array([-20.81347085,   3.7313799 ,   0.        ])
v_inf_d = array([7.1623017 , 1.92406857, 0.        ]) v_inf_a = array([3.31686124, 3.7313799 , 0.        ])
[2.74876308]
Vd = array([ 7.16141164, 31.7077309 ,  0.        ]) Va = array([-20.81385056,   3.7324687 ,   0.        ])
v_inf_d = array([7.16141164, 1.92464701, 0.        ]) v_inf_a = array([3.31648153, 3.7324687 , 0.        ])
[2.74867883]
Vd = array([ 7.16111494, 31.70792372,  0.        ]) Va = array([-20.81397713,   3.73283165,   0.        ])
v_inf_d = array([7.16111494, 1.92483984, 0.        ]) v_inf_a = array([3.31635496, 3.73283165, 0.        ])
[2.7488052]
Vd = array([ 7.16155999, 31.70763449,  0.        ]) Va = array([-20.81378727,   3.73228723,   0.        ])
v_inf_d = array([7.16155999, 1.9245506 , 0.        ]) v_inf_a = array([3.31654482, 3.73228723, 0.        ])
[2.74872095]
Vd = array([ 7.16126329, 31.70782731,  0.        ]) Va = array([-20.81391385,   3.73265017,   0.        ])
v_inf_d = array([7.16126329, 1.92474343, 0.        ]) v_inf_a = array([3.31641824, 3.73265017, 0.        ])
[2.74878414]
Vd = array([ 7.16148582, 31.70768269,  0.        ]) Va = array([-20.81381891,   3.73237796,   0.        ])
v_inf_d = array([7.16148582, 1.92459881, 0.        ]) v_inf_a = array([3.31651317, 3.73237796, 0.        ])
[2.7488052]
Vd = array([ 7.16155999, 31.70763449,  0.        ]) Va = array([-20.81378727,   3.73228723,   0.        ])
v_inf_d = array([7.16155999, 1.9245506 , 0.        ]) v_inf_a = array([3.31654482, 3.73228723, 0.        ])
[2.74877361]
Vd = array([ 7.16144873, 31.70770679,  0.        ]) Va = array([-20.81383474,   3.73242333,   0.        ])
v_inf_d = array([7.16144873, 1.92462291, 0.        ]) v_inf_a = array([3.31649735, 3.73242333, 0.        ])
[2.74876308]
Vd = array([ 7.16141164, 31.7077309 ,  0.        ]) Va = array([-20.81385056,   3.7324687 ,   0.        ])
v_inf_d = array([7.16141164, 1.92464701, 0.        ]) v_inf_a = array([3.31648153, 3.7324687 , 0.        ])
[2.74877887]
Vd = array([ 7.16146727, 31.70769474,  0.        ]) Va = array([-20.81382683,   3.73240065,   0.        ])
v_inf_d = array([7.16146727, 1.92461086, 0.        ]) v_inf_a = array([3.31650526, 3.73240065, 0.        ])
[2.74878414]
Vd = array([ 7.16148582, 31.70768269,  0.        ]) Va = array([-20.81381891,   3.73237796,   0.        ])
v_inf_d = array([7.16148582, 1.92459881, 0.        ]) v_inf_a = array([3.31651317, 3.73237796, 0.        ])
[2.74877624]
Vd = array([ 7.161458  , 31.70770077,  0.        ]) Va = array([-20.81383078,   3.73241199,   0.        ])
v_inf_d = array([7.161458  , 1.92461689, 0.        ]) v_inf_a = array([3.31650131, 3.73241199, 0.        ])
[8.28532143]
Vd = array([20.39726674, 24.46981104,  0.        ]) Va = array([-15.84720899, -12.41643237,  -0.        ])
v_inf_d = array([20.39726674, -5.31327284,  0.        ]) v_inf_a = array([  8.27940675, -11.99294755,  -0.        ])
[8.64564937]
Vd = array([21.01003048, 24.19116787,  0.        ]) Va = array([-15.65192308, -13.11994549,  -0.        ])
v_inf_d = array([21.01003048, -5.59191602,  0.        ]) v_inf_a = array([  8.47469267, -12.69646067,  -0.        ])
[7.90692061]
Vd = array([19.7292096 , 24.77867639,  0.        ]) Va = array([-16.06347999, -11.64778126,  -0.        ])
v_inf_d = array([19.7292096 , -5.00440749,  0.        ]) v_inf_a = array([  8.06313576, -11.22429644,  -0.        ])
[7.50888434]
Vd = array([18.99761644, 25.12308108,  0.        ]) Va = array([-16.30440203, -10.80401732,  -0.        ])
v_inf_d = array([18.99761644, -4.6600028 ,  0.        ]) v_inf_a = array([  7.82221371, -10.38053251,  -0.        ])
[6.64675462]
Vd = array([17.30152455, 25.94685168,  0.        ]) Va = array([-16.87971191,  -8.83961944,  -0.        ])
v_inf_d = array([17.30152455, -3.83623221,  0.        ]) v_inf_a = array([ 7.24690383, -8.41613462, -0.        ])
[5.68258385]
Vd = array([15.19726484, 27.01950232,  0.        ]) Va = array([-17.62700638,  -6.38597626,  -0.        ])
v_inf_d = array([15.19726484, -2.76358156,  0.        ]) v_inf_a = array([ 6.49960936, -5.96249145, -0.        ])
[3.36586705]
Vd = array([ 8.92706564, 30.56783912,  0.        ]) Va = array([-20.08694052,   1.04009256,   0.        ])
v_inf_d = array([8.92706564, 0.78475524, 0.        ]) v_inf_a = array([4.03967523, 1.46357738, 0.        ])
[0.40202952]
Vd = array([-3.82228991, 39.54008507,  0.        ]) Va = array([-26.25257733,  16.71263277,   0.        ])
v_inf_d = array([-3.82228991,  9.75700119,  0.        ]) v_inf_a = array([-2.12596158, 17.13611758,  0.        ])
[0.40202952]
Vd = array([-3.82228991, 39.54008507,  0.        ]) Va = array([-26.25257733,  16.71263277,   0.        ])
v_inf_d = array([-3.82228991,  9.75700119,  0.        ]) v_inf_a = array([-2.12596158, 17.13611758,  0.        ])
[4.59653383]
Vd = array([12.50687928, 28.47582749,  0.        ]) Va = array([-18.63867648,  -3.22121123,  -0.        ])
v_inf_d = array([12.50687928, -1.3072564 ,  0.        ]) v_inf_a = array([ 5.48793927, -2.79772641, -0.        ])
[1.96909668]
Vd = array([ 3.89047601, 33.82308574,  0.        ]) Va = array([-22.3311254 ,   7.13718802,   0.        ])
v_inf_d = array([3.89047601, 4.04000185, 0.        ]) v_inf_a = array([1.79549034, 7.56067284, 0.        ])
[2.68925382]
Vd = array([ 6.64392377, 31.99744775,  0.        ]) Va = array([-21.07377045,   3.78896646,   0.        ])
v_inf_d = array([6.64392377, 2.21436387, 0.        ]) v_inf_a = array([3.05284529, 4.21245127, 0.        ])
[1.96909668]
Vd = array([ 3.89047601, 33.82308574,  0.        ]) Va = array([-22.3311254 ,   7.13718802,   0.        ])
v_inf_d = array([3.89047601, 4.04000185, 0.        ]) v_inf_a = array([1.79549034, 7.56067284, 0.        ])
[3.03291892]
Vd = array([ 7.83607167, 31.24155382,  0.        ]) Va = array([-20.55225619,   2.35056422,   0.        ])
v_inf_d = array([7.83607167, 1.45846993, 0.        ]) v_inf_a = array([3.57435956, 2.77404904, 0.        ])
[2.33467535]
Vd = array([ 5.33507075, 32.85129664,  0.        ]) Va = array([-21.66220374,   5.37599129,   0.        ])
v_inf_d = array([5.33507075, 3.06821276, 0.        ]) v_inf_a = array([2.46441201, 5.79947611, 0.        ])
[2.86244037]
Vd = array([ 7.25354251, 31.60832718,  0.        ]) Va = array([-20.80537587,   3.0525798 ,   0.        ])
v_inf_d = array([7.25354251, 1.8252433 , 0.        ]) v_inf_a = array([3.32123987, 3.47606462, 0.        ])
[3.03291892]
Vd = array([ 7.83607167, 31.24155382,  0.        ]) Va = array([-20.55225619,   2.35056422,   0.        ])
v_inf_d = array([7.83607167, 1.45846993, 0.        ]) v_inf_a = array([3.57435956, 2.77404904, 0.        ])
[2.77618712]
Vd = array([ 6.95224165, 31.79996994,  0.        ]) Va = array([-20.93757945,   3.41631397,   0.        ])
v_inf_d = array([6.95224165, 2.01688605, 0.        ]) v_inf_a = array([3.1890363 , 3.83979879, 0.        ])
[2.68925382]
Vd = array([ 6.64392377, 31.99744775,  0.        ]) Va = array([-21.07377045,   3.78896646,   0.        ])
v_inf_d = array([6.64392377, 2.21436387, 0.        ]) v_inf_a = array([3.05284529, 4.21245127, 0.        ])
[2.81939857]
Vd = array([ 7.10375345, 31.70343525,  0.        ]) Va = array([-20.87099016,   3.2333531 ,   0.        ])
v_inf_d = array([7.10375345, 1.92035137, 0.        ]) v_inf_a = array([3.25562559, 3.65683791, 0.        ])
[2.86244037]
Vd = array([ 7.25354251, 31.60832718,  0.        ]) Va = array([-20.80537587,   3.0525798 ,   0.        ])
v_inf_d = array([7.25354251, 1.8252433 , 0.        ]) v_inf_a = array([3.32123987, 3.47606462, 0.        ])
[2.79781408]
Vd = array([ 7.02821483, 31.7515223 ,  0.        ]) Va = array([-20.90416158,   3.32455751,   0.        ])
v_inf_d = array([7.02821483, 1.96843841, 0.        ]) v_inf_a = array([3.22245416, 3.74804232, 0.        ])
[2.77618712]
Vd = array([ 6.95224165, 31.79996994,  0.        ]) Va = array([-20.93757945,   3.41631397,   0.        ])
v_inf_d = array([6.95224165, 2.01688605, 0.        ]) v_inf_a = array([3.1890363 , 3.83979879, 0.        ])
[2.80861163]
Vd = array([ 7.06603822, 31.72743395,  0.        ]) Va = array([-20.88754523,   3.27888662,   0.        ])
v_inf_d = array([7.06603822, 1.94435007, 0.        ]) v_inf_a = array([3.23907051, 3.70237144, 0.        ])
[2.78700591]
Vd = array([ 6.99028281, 31.77570079,  0.        ]) Va = array([-20.92083954,   3.37036641,   0.        ])
v_inf_d = array([6.99028281, 1.99261691, 0.        ]) v_inf_a = array([3.2057762 , 3.79385122, 0.        ])
[2.80321418]
Vd = array([ 7.04714007, 31.73946689,  0.        ]) Va = array([-20.89584573,   3.30170485,   0.        ])
v_inf_d = array([7.04714007, 1.956383  , 0.        ]) v_inf_a = array([3.23077002, 3.72518967, 0.        ])
[2.80861163]
Vd = array([ 7.06603822, 31.72743395,  0.        ]) Va = array([-20.88754523,   3.27888662,   0.        ])
v_inf_d = array([7.06603822, 1.94435007, 0.        ]) v_inf_a = array([3.23907051, 3.70237144, 0.        ])
[2.80051446]
Vd = array([ 7.03768084, 31.74549178,  0.        ]) Va = array([-20.90000173,   3.31312687,   0.        ])
v_inf_d = array([7.03768084, 1.96240789, 0.        ]) v_inf_a = array([3.22661401, 3.73661169, 0.        ])
[2.80591324]
Vd = array([ 7.05659253, 31.73344761,  0.        ]) Va = array([-20.89169357,   3.29029144,   0.        ])
v_inf_d = array([7.05659253, 1.95036373, 0.        ]) v_inf_a = array([3.23492218, 3.71377625, 0.        ])
[2.8018644]
Vd = array([ 7.04241131, 31.74247863,  0.        ]) Va = array([-20.89792325,   3.30741478,   0.        ])
v_inf_d = array([7.04241131, 1.95939475, 0.        ]) v_inf_a = array([3.22869249, 3.7308996 , 0.        ])
[2.80051446]
Vd = array([ 7.03768084, 31.74549178,  0.        ]) Va = array([-20.90000173,   3.31312687,   0.        ])
v_inf_d = array([7.03768084, 1.96240789, 0.        ]) v_inf_a = array([3.22661401, 3.73661169, 0.        ])
[2.80253931]
Vd = array([ 7.0447759 , 31.74097258,  0.        ]) Va = array([-20.89688437,   3.30455955,   0.        ])
v_inf_d = array([7.0447759, 1.9578887, 0.       ]) v_inf_a = array([3.22973137, 3.72804437, 0.        ])
[2.80118945]
Vd = array([ 7.04004629, 31.74398503,  0.        ]) Va = array([-20.89896237,   3.31027056,   0.        ])
v_inf_d = array([7.04004629, 1.96090114, 0.        ]) v_inf_a = array([3.22765337, 3.73375538, 0.        ])
[2.80220186]
Vd = array([ 7.04359366, 31.74172556,  0.        ]) Va = array([-20.89740378,   3.3059871 ,   0.        ])
v_inf_d = array([7.04359366, 1.95864168, 0.        ]) v_inf_a = array([3.22921196, 3.72947192, 0.        ])
[2.80253931]
Vd = array([ 7.0447759 , 31.74097258,  0.        ]) Va = array([-20.89688437,   3.30455955,   0.        ])
v_inf_d = array([7.0447759, 1.9578887, 0.       ]) v_inf_a = array([3.22973137, 3.72804437, 0.        ])
[2.80203313]
Vd = array([ 7.0430025 , 31.74210208,  0.        ]) Va = array([-20.89766351,   3.30670093,   0.        ])
v_inf_d = array([7.0430025, 1.9590182, 0.       ]) v_inf_a = array([3.22895224, 3.73018574, 0.        ])
[2.80237059]
Vd = array([ 7.04418479, 31.74134906,  0.        ]) Va = array([-20.89714407,   3.30527331,   0.        ])
v_inf_d = array([7.04418479, 1.95826518, 0.        ]) v_inf_a = array([3.22947168, 3.72875812, 0.        ])
[2.8021175]
Vd = array([ 7.04329808, 31.74191382,  0.        ]) Va = array([-20.89753364,   3.30634401,   0.        ])
v_inf_d = array([7.04329808, 1.95882994, 0.        ]) v_inf_a = array([3.2290821 , 3.72982883, 0.        ])
[2.80203313]
Vd = array([ 7.0430025 , 31.74210208,  0.        ]) Va = array([-20.89766351,   3.30670093,   0.        ])
v_inf_d = array([7.0430025, 1.9590182, 0.       ]) v_inf_a = array([3.22895224, 3.73018574, 0.        ])
[2.80215968]

In [69]:
result_shaped = np.reshape(result, (-1, 2))
result_shaped
df = pd.DataFrame(result_shaped)
with pd.ExcelWriter("output.xlsx") as writer:
    df.to_excel(writer, sheet_name="Sheet_name_1")

In [73]:
df.columns = ["anomaly", "time of flight"]
df

        anomaly  time of flight
0     90.000000      136.082439
1     91.005587      137.437935
2     92.011173      138.795147
3     93.016760      140.154018
4     94.022346      141.514492
..          ...             ...
175  265.977654      362.660637
176  266.983240      363.557568
177  267.988827      364.436874
178  268.994413      365.297699
179  270.000000      366.139183

[180 rows x 2 columns]

In [74]:
delta_vs = []
for index, row in df.iterrows():
    res = simulate(row["anomaly"], row["time of flight"])
    delta_vs.append(res)

2.7487762398556335
Vd = array([ 7.161458  , 31.70770077,  0.        ]) Va = array([-20.81383078,   3.73241199,   0.        ])
v_inf_d = array([7.161458  , 1.92461689, 0.        ]) v_inf_a = array([3.31650131, 3.73241199, 0.        ])
2.802154408096544
Vd = array([ 7.0434274 , 31.74183146,  0.        ]) Va = array([-20.89747683,   3.30618786,   0.        ])
v_inf_d = array([7.0434274 , 1.95874757, 0.        ]) v_inf_a = array([3.22913892, 3.72967268, 0.        ])
2.8561492513623925
Vd = array([ 6.9271342 , 31.77483408,  0.        ]) Va = array([-20.97185257,   2.8789497 ,   0.        ])
v_inf_d = array([6.9271342, 1.9917502, 0.       ]) v_inf_a = array([3.14361529, 3.72578889, 0.        ])
2.9107604297572522
Vd = array([ 6.81253065, 31.80675284,  0.        ]) Va = array([-21.03699005,   2.45088385,   0.        ])
v_inf_d = array([6.81253065, 2.02366895, 0.        ]) v_inf_a = array([3.05990181, 3.72081657, 0.        ])
2.9659875071599227
Vd = array([ 6.69957001, 31.83763002,  0.        ]) Va = array([-21.09292332,   2.02217497,   0.        ])
v_inf_d = array([6.69957001, 2.05454613, 0.        ]) v_inf_a = array([2.97797017, 3.71481005, 0.        ])
3.0218273072669652
Vd = array([ 6.58819753, 31.86751147,  0.        ]) Va = array([-21.13969288,   1.5930164 ,   0.        ])
v_inf_d = array([6.58819753, 2.08442758, 0.        ]) v_inf_a = array([2.89778785, 3.70783247, 0.        ])
3.0782792072941145
Vd = array([ 6.47836865, 31.89643558,  0.        ]) Va = array([-21.17733709,   1.16358887,   0.        ])
v_inf_d = array([6.47836865, 2.11335169, 0.        ]) v_inf_a = array([2.8193268 , 3.69993452, 0.        ])
3.13533985016956
Vd = array([ 6.37003084, 31.92444417,  0.        ]) Va = array([-21.20590095,   0.73408148,   0.        ])
v_inf_d = array([6.37003084, 2.14136028, 0.        ]) v_inf_a = array([2.74255457, 3.69117545, 0.        ])
3.1930111012776528
Vd = array([ 6.26315063, 31.95156708,  0.        ]) Va = array([-21.22542246,   0.30466118,   0.        ])
v_inf_d = array([6.26315063, 2.1684832 , 0.        ]) v_inf_a = array([2.66744804, 3.68159263, 0.        ])
3.2512894486310193
Vd = array([ 6.15767752, 31.9778428 ,  0.        ]) Va = array([-21.23595085,  -0.12448663,  -0.        ])
v_inf_d = array([6.15767752, 2.19475892, 0.        ]) v_inf_a = array([ 2.59397509,  3.67124213, -0.        ])
3.3101766169265776
Vd = array([ 6.05357987, 32.00329848,  0.        ]) Va = array([-21.23752804,  -0.55319797,  -0.        ])
v_inf_d = array([6.05357987, 2.2202146 , 0.        ]) v_inf_a = array([ 2.52211317,  3.66015893, -0.        ])
3.3696662991030815
Vd = array([ 5.95080035, 32.02797413,  0.        ]) Va = array([-21.23021243,  -0.9812818 ,  -0.        ])
v_inf_d = array([5.95080035, 2.24489024, 0.        ]) v_inf_a = array([ 2.45182555,  3.64840542, -0.        ])
3.4297627482572124
Vd = array([ 5.84931798, 32.05188957,  0.        ]) Va = array([-21.21404514,  -1.40858682,  -0.        ])
v_inf_d = array([5.84931798, 2.26880569, 0.        ]) v_inf_a = array([ 2.38309501,  3.63600467, -0.        ])
3.490459534484287
Vd = array([ 5.74907743, 32.07508177,  0.        ]) Va = array([-21.18908895,  -1.83492608,  -0.        ])
v_inf_d = array([5.74907743, 2.29199789, 0.        ]) v_inf_a = array([ 2.31588492,  3.62301585, -0.        ])
3.551760799110677
Vd = array([ 5.6500593 , 32.09756853,  0.        ]) Va = array([-21.15538881,  -2.26015093,  -0.        ])
v_inf_d = array([5.6500593 , 2.31448465, 0.        ]) v_inf_a = array([ 2.25017871,  3.60946026, -0.        ])
3.613662661529793
Vd = array([ 5.55221882, 32.11937982,  0.        ]) Va = array([-21.11300671,  -2.68408714,  -0.        ])
v_inf_d = array([5.55221882, 2.33629594, 0.        ]) v_inf_a = array([ 2.18594503,  3.59538534, -0.        ])
3.6761638495588698
Vd = array([ 5.45552083, 32.14054   ,  0.        ]) Va = array([-21.0620017 ,  -3.10657134,  -0.        ])
v_inf_d = array([5.45552083, 2.35745611, 0.        ]) v_inf_a = array([ 2.12315765,  3.58082821, -0.        ])
3.739263045976206
Vd = array([ 5.35993098, 32.16107235,  0.        ]) Va = array([-21.00243489,  -3.52744186,  -0.        ])
v_inf_d = array([5.35993098, 2.37798847, 0.        ]) v_inf_a = array([ 2.06179052,  3.56582488, -0.        ])
3.8029615449945195
Vd = array([ 5.2654242 , 32.18099531,  0.        ]) Va = array([-20.93436411,  -3.94654695,  -0.        ])
v_inf_d = array([5.2654242 , 2.39791143, 0.        ]) v_inf_a = array([ 2.00182305,  3.55040211, -0.        ])
3.867257944321637
Vd = array([ 5.17196759, 32.20033043,  0.        ]) Va = array([-20.85785438,  -4.36372791,  -0.        ])
v_inf_d = array([5.17196759, 2.41724655, 0.        ]) v_inf_a = array([ 1.94322967,  3.53459423, -0.        ])
3.9321481541181535
Vd = array([ 5.07952069, 32.21910196,  0.        ]) Va = array([-20.77297819,  -4.77882003,  -0.        ])
v_inf_d = array([5.07952069, 2.43601807, 0.        ]) v_inf_a = array([ 1.88597951,  3.51844233, -0.        ])
3.997636002770872
Vd = array([ 4.98806887, 32.2373222 ,  0.        ]) Va = array([-20.67979384,  -5.19168398,  -0.        ])
v_inf_d = array([4.98806887, 2.45423832, 0.        ]) v_inf_a = array([ 1.83005803,  3.50196286, -0.        ])
4.0637173328609375
Vd = array([ 4.89757311, 32.25501369,  0.        ]) Va = array([-20.57837783,  -5.60215843,  -0.        ])
v_inf_d = array([4.89757311, 2.47192981, 0.        ]) v_inf_a = array([ 1.77543468,  3.48519504, -0.        ])
4.130390610123535
Vd = array([ 4.80800353, 32.27219438,  0.        ]) Va = array([-20.46880324,  -6.01009187,  -0.        ])
v_inf_d = array([4.80800353, 2.4891105 , 0.        ]) v_inf_a = array([ 1.72208441,  3.46816913, -0.        ])
4.197659556744035
Vd = array([ 4.71934716, 32.28887487,  0.        ]) Va = array([-20.35113407,  -6.41534896,  -0.        ])
v_inf_d = array([4.71934716, 2.50579099, 0.        ]) v_inf_a = array([ 1.66999345,  3.45090005, -0.        ])
4.2655199337290215
Vd = array([ 4.63156712, 32.30507521,  0.        ]) Va = array([-20.22545278,  -6.81777387,  -0.        ])
v_inf_d = array([4.63156712, 2.52199133, 0.        ]) v_inf_a = array([ 1.6191316 ,  3.43342412, -0.        ])
4.333972761574804
Vd = array([ 4.54464345, 32.32080816,  0.        ]) Va = array([-20.09183269,  -7.21722702,  -0.        ])
v_inf_d = array([4.54464345, 2.53772428, 0.        ]) v_inf_a = array([ 1.56947991,  3.41576236, -0.        ])
4.403013763753905
Vd = array([ 4.45854071, 32.33609211,  0.        ]) Va = array([-19.95036029,  -7.61355665,  -0.        ])
v_inf_d = array([4.45854071, 2.55300823, 0.        ]) v_inf_a = array([ 1.52100837,  3.39794892, -0.        ])
4.47264654546171
Vd = array([ 4.37324801, 32.35093562,  0.        ]) Va = array([-19.80110706,  -8.00663321,  -0.        ])
v_inf_d = array([4.37324801, 2.56785174, 0.        ]) v_inf_a = array([ 1.47370399,  3.37999674, -0.        ])
4.54286941764918
Vd = array([ 4.28873898, 32.36535293,  0.        ]) Va = array([-19.64415761,  -8.39631506,  -0.        ])
v_inf_d = array([4.28873898, 2.58226905, 0.        ]) v_inf_a = array([ 1.42754271,  3.36193194, -0.        ])
4.613680676290389
Vd = array([ 4.20498789, 32.37935761,  0.        ]) Va = array([-19.47959849,  -8.78246248,  -0.        ])
v_inf_d = array([4.20498789, 2.59627372, 0.        ]) v_inf_a = array([ 1.38250054,  3.34377977, -0.        ])
4.685078604635743
Vd = array([ 4.12196959, 32.39296258,  0.        ]) Va = array([-19.30751814,  -9.16493773,  -0.        ])
v_inf_d = array([4.12196959, 2.6098787 , 0.        ]) v_inf_a = array([ 1.3385536 ,  3.32556461, -0.        ])
4.757066702075295
Vd = array([ 4.03967484, 32.40617496,  0.        ]) Va = array([-19.12799532,  -9.543617  ,  -0.        ])
v_inf_d = array([4.03967484, 2.62309107, 0.        ]) v_inf_a = array([ 1.29568967,  3.30729807, -0.        ])
4.82964059783842
Vd = array([ 3.95807174, 32.41900946,  0.        ]) Va = array([-18.94112791,  -9.91835984,  -0.        ])
v_inf_d = array([3.95807174, 2.63592558, 0.        ]) v_inf_a = array([ 1.25387938,  3.28900959, -0.        ])
4.902801139672732
Vd = array([ 3.87714427, 32.43147501,  0.        ]) Va = array([-18.74700406, -10.28903979,  -0.        ])
v_inf_d = array([3.87714427, 2.64839112, 0.        ]) v_inf_a = array([ 1.21310501,  3.27071583, -0.        ])
4.976546551313172
Vd = array([ 3.79686924, 32.44358266,  0.        ]) Va = array([-18.54571953, -10.65552631,  -0.        ])
v_inf_d = array([3.79686924, 2.66049877, 0.        ]) v_inf_a = array([ 1.17334316,  3.25243879, -0.        ])
5.050880241904918
Vd = array([ 3.71723884, 32.45533829,  0.        ]) Va = array([-18.33736019, -11.01770175,  -0.        ])
v_inf_d = array([3.71723884, 2.67225441, 0.        ]) v_inf_a = array([ 1.1345822 ,  3.23418886, -0.        ])
5.125795217946004
Vd = array([ 3.63821591, 32.46675682,  0.        ]) Va = array([-18.122037  , -11.37542838,  -0.        ])
v_inf_d = array([3.63821591, 2.68367294, 0.        ]) v_inf_a = array([ 1.09678729,  3.21599785, -0.        ])
5.201297448559159
Vd = array([ 3.55980076, 32.47784122,  0.        ]) Va = array([-17.89983349, -11.72859732,  -0.        ])
v_inf_d = array([3.55980076, 2.69475734, 0.        ]) v_inf_a = array([ 1.05995288,  3.19787003, -0.        ])
5.277382521932168
Vd = array([ 3.48196456, 32.48860323,  0.        ]) Va = array([-17.67085827, -12.07708024,  -0.        ])
v_inf_d = array([3.48196456, 2.70551934, 0.        ]) v_inf_a = array([ 1.02405013,  3.17983055, -0.        ])
5.354051196036688
Vd = array([ 3.40469356, 32.49904974,  0.        ]) Va = array([-17.43520996, -12.42076119,  -0.        ])
v_inf_d = array([3.40469356, 2.71596586, 0.        ]) v_inf_a = array([ 0.98906202,  3.16189355, -0.        ])
5.431301640377694
Vd = array([ 3.32796716, 32.50918947,  0.        ]) Va = array([-17.19299471, -12.75952118,  -0.        ])
v_inf_d = array([3.32796716, 2.72610559, 0.        ]) v_inf_a = array([ 0.95496576,  3.14407772, -0.        ])
5.509137153000709
Vd = array([ 3.25177935, 32.51902683,  0.        ]) Va = array([-16.9443086 , -13.09325257,  -0.        ])
v_inf_d = array([3.25177935, 2.73594294, 0.        ]) v_inf_a = array([ 0.92175037,  3.1263918 , -0.        ])
5.587553319135836
Vd = array([ 3.17610311, 32.52857187,  0.        ]) Va = array([-16.68926696, -13.42183554,  -0.        ])
v_inf_d = array([3.17610311, 2.74548799, 0.        ]) v_inf_a = array([ 0.88938736,  3.1088583 , -0.        ])
5.666550854262454
Vd = array([ 3.10092602, 32.5378304 ,  0.        ]) Va = array([-16.42797499, -13.74516167,  -0.        ])
v_inf_d = array([3.10092602, 2.75474652, 0.        ]) v_inf_a = array([ 0.85786007,  3.09148981, -0.        ])
5.746130456122069
Vd = array([ 3.02623585, 32.54680806,  0.        ]) Va = array([-16.16053945, -14.06312431,  -0.        ])
v_inf_d = array([3.02623585, 2.76372418, 0.        ]) v_inf_a = array([ 0.8271519 ,  3.07429875, -0.        ])
5.826290266485478
Vd = array([ 2.95201376, 32.55551202,  0.        ]) Va = array([-15.88707459, -14.37561449,  -0.        ])
v_inf_d = array([2.95201376, 2.77242814, 0.        ]) v_inf_a = array([ 0.79724048,  3.05730143, -0.        ])
5.907030967203512
Vd = array([ 2.87824812, 32.56394745,  0.        ]) Va = array([-15.60769027, -14.6825295 ,  -0.        ])
v_inf_d = array([2.87824812, 2.78086357, 0.        ]) v_inf_a = array([ 0.76810937,  3.04050954, -0.        ])
5.9883506980701995
Vd = array([ 2.80492075, 32.57212092,  0.        ]) Va = array([-15.32250376, -14.98376464,  -0.        ])
v_inf_d = array([2.80492075, 2.78903704, 0.        ]) v_inf_a = array([ 0.73973633,  3.02393844, -0.        ])
6.070250127704667
Vd = array([ 2.73202056, 32.58003717,  0.        ]) Va = array([-15.03162795, -15.27922124,  -0.        ])
v_inf_d = array([2.73202056, 2.79695328, 0.        ]) v_inf_a = array([ 0.71210506,  3.00759909, -0.        ])
6.152729908990028
Vd = array([ 2.65953662, 32.58770078,  0.        ]) Va = array([-14.7351772 , -15.56880253,  -0.        ])
v_inf_d = array([2.65953662, 2.80461689, 0.        ]) v_inf_a = array([ 0.6851993,  2.9915023, -0.       ])
6.235788173996739
Vd = array([ 2.58745163, 32.59511762,  0.        ]) Va = array([-14.43327314, -15.85241014,  -0.        ])
v_inf_d = array([2.58745163, 2.81203374, 0.        ]) v_inf_a = array([ 0.65899703,  2.97566219, -0.        ])
6.319423067130678
Vd = array([ 2.51574866, 32.60229323,  0.        ]) Va = array([-14.12603877, -16.12994812,  -0.        ])
v_inf_d = array([2.51574866, 2.81920935, 0.        ]) v_inf_a = array([ 0.63347631,  2.96009225, -0.        ])
6.403637728461105
Vd = array([ 2.44442403, 32.60923025,  0.        ]) Va = array([-13.81358687, -16.4013294 ,  -0.        ])
v_inf_d = array([2.44442403, 2.82614636, 0.        ]) v_inf_a = array([ 0.60862685,  2.94479884, -0.        ])
6.488430287315324
Vd = array([ 2.37346123, 32.61593388,  0.        ]) Va = array([-13.49604318, -16.66646218,  -0.        ])
v_inf_d = array([2.37346123, 2.83284999, 0.        ]) v_inf_a = array([ 0.58442682,  2.92979489, -0.        ])
6.573798887415493
Vd = array([ 2.30284409, 32.62240903,  0.        ]) Va = array([-13.17353472, -16.92525709,  -0.        ])
v_inf_d = array([2.30284409, 2.83932515, 0.        ]) v_inf_a = array([ 0.56085446,  2.91509272, -0.        ])
6.659744157154165
Vd = array([ 2.23256308, 32.62865919,  0.        ]) Va = array([-12.84618401, -17.17763014,  -0.        ])
v_inf_d = array([2.23256308, 2.84557531, 0.        ]) v_inf_a = array([ 0.53789385,  2.90070113, -0.        ])
6.746266711430983
Vd = array([ 2.16260878, 32.63468772,  0.        ]) Va = array([-12.51411487, -17.42349938,  -0.        ])
v_inf_d = array([2.16260878, 2.85160384, 0.        ]) v_inf_a = array([ 0.51552907,  2.88662877, -0.        ])
6.833364697472109
Vd = array([ 2.09296573, 32.64049896,  0.        ]) Va = array([-12.17745805, -17.66278223,  -0.        ])
v_inf_d = array([2.09296573, 2.85741508, 0.        ]) v_inf_a = array([ 0.49373854,  2.87288684, -0.        ])
6.921038726215805
Vd = array([ 2.02362489, 32.64609598,  0.        ]) Va = array([-11.83633978, -17.89540118,  -0.        ])
v_inf_d = array([2.02362489, 2.8630121 , 0.        ]) v_inf_a = array([ 0.47250644,  2.85948333, -0.        ])
7.009289395686954
Vd = array([ 1.95457735, 32.65148175,  0.        ]) Va = array([-11.49088748, -18.12128086,  -0.        ])
v_inf_d = array([1.95457735, 2.86839786, 0.        ]) v_inf_a = array([ 0.45181698,  2.84642614, -0.        ])
7.098112429051914
Vd = array([ 1.88580228, 32.65666101,  0.        ]) Va = array([-11.14124098, -18.34034324,  -0.        ])
v_inf_d = array([1.88580228, 2.87357712, 0.        ]) v_inf_a = array([ 0.43164309,  2.83372772, -0.        ])
7.187510869026102
Vd = array([ 1.8172972 , 32.66163543,  0.        ]) Va = array([-10.78752425, -18.55252007,  -0.        ])
v_inf_d = array([1.8172972 , 2.87855155, 0.        ]) v_inf_a = array([ 0.41197473,  2.82139275, -0.        ])
7.27748529934678
Vd = array([ 1.74905363, 32.66640763,  0.        ]) Va = array([-10.42986801, -18.7577427 ,  -0.        ])
v_inf_d = array([1.74905363, 2.88332374, 0.        ]) v_inf_a = array([ 0.39279617,  2.80942834, -0.        ])
7.368031477264791
Vd = array([ 1.68105148, 32.67098174,  0.        ]) Va = array([-10.06841518, -18.9559405 ,  -0.        ])
v_inf_d = array([1.68105148, 2.88789786, 0.        ]) v_inf_a = array([ 0.37408058,  2.79784559, -0.        ])
7.459152409306542
Vd = array([ 1.61328852, 32.67535923,  0.        ]) Va = array([ -9.7032929 , -19.14705173,  -0.        ])
v_inf_d = array([1.61328852, 2.89227535, 0.        ]) v_inf_a = array([ 0.35581792,  2.78664874, -0.        ])
7.55084627621158
Vd = array([ 1.5457509, 32.6795431,  0.       ]) Va = array([ -9.33464042, -19.33101275,  -0.        ])
v_inf_d = array([1.5457509 , 2.89645922, 0.        ]) v_inf_a = array([ 0.33798703,  2.77584603, -0.        ])
7.643113662150994
Vd = array([ 1.47843073, 32.68353545,  0.        ]) Va = array([ -8.96259236, -19.50776428,  -0.        ])
v_inf_d = array([1.47843073, 2.90045157, 0.        ]) v_inf_a = array([ 0.32057232,  2.7654434 , -0.        ])
7.73595039150142
Vd = array([ 1.41130893, 32.6873396 ,  0.        ]) Va = array([ -8.58729515, -19.67724593,  -0.        ])
v_inf_d = array([1.41130893, 2.90425572, 0.        ]) v_inf_a = array([ 0.30354734,  2.75545   , -0.        ])
7.829361806738646
Vd = array([ 1.34438918, 32.69095608,  0.        ]) Va = array([ -8.20887426, -19.83940667,  -0.        ])
v_inf_d = array([1.34438918, 2.90787219, 0.        ]) v_inf_a = array([ 0.28690746,  2.74586773, -0.        ])
7.923343742865215
Vd = array([ 1.27765269, 32.69438795,  0.        ]) Va = array([ -7.82747774, -19.99419102,  -0.        ])
v_inf_d = array([1.27765269, 2.91130407, 0.        ]) v_inf_a = array([ 0.27062631,  2.73670508, -0.        ])
8.017896788585501
Vd = array([ 1.21109209, 32.69763686,  0.        ]) Va = array([ -7.44324355, -20.1415493 ,  -0.        ])
v_inf_d = array([1.21109209, 2.91455298, 0.        ]) v_inf_a = array([ 0.25468845,  2.72796686, -0.        ])
8.113019181405374
Vd = array([ 1.14469461, 32.70070491,  0.        ]) Va = array([ -7.05631571, -20.28143284,  -0.        ])
v_inf_d = array([1.14469461, 2.91762102, 0.        ]) v_inf_a = array([ 0.23907309,  2.71965907, -0.        ])
8.208713844960457
Vd = array([ 1.07845845, 32.70359303,  0.        ]) Va = array([ -6.66682834, -20.41379808,  -0.        ])
v_inf_d = array([1.07845845, 2.92050915, 0.        ]) v_inf_a = array([ 0.22377012,  2.71178471, -0.        ])
8.304976689057627
Vd = array([ 1.01236569, 32.70630362,  0.        ]) Va = array([ -6.27493211, -20.5386    ,  -0.        ])
v_inf_d = array([1.01236569, 2.92321973, 0.        ]) v_inf_a = array([ 0.20875354,  2.70435048, -0.        ])
8.401810623937179
Vd = array([ 0.94641463, 32.70883748,  0.        ]) Va = array([ -5.8807625 , -20.65579977,  -0.        ])
v_inf_d = array([0.94641463, 2.92575359, 0.        ]) v_inf_a = array([ 0.19401323,  2.69735904, -0.        ])
8.499213903554248
Vd = array([ 0.88059296, 32.71119627,  0.        ]) Va = array([ -5.48446609, -20.76535864,  -0.        ])
v_inf_d = array([0.88059296, 2.92811239, 0.        ]) v_inf_a = array([ 0.17952855,  2.6908152 , -0.        ])
8.597184806080199
Vd = array([ 0.81488857, 32.7133815 ,  0.        ]) Va = array([ -5.08618992, -20.86724052,  -0.        ])
v_inf_d = array([0.81488857, 2.93029761, 0.        ]) v_inf_a = array([ 0.165279  ,  2.68472333, -0.        ])
8.695723921621918
Vd = array([ 0.74929468, 32.71539415,  0.        ]) Va = array([ -4.68607635, -20.96141282,  -0.        ])
v_inf_d = array([0.74929468, 2.93231026, 0.        ]) v_inf_a = array([ 0.15124926,  2.67908649, -0.        ])
8.794829551077047
Vd = array([ 0.68379943, 32.71723547,  0.        ]) Va = array([ -4.28427334, -21.0478446 ,  -0.        ])
v_inf_d = array([0.68379943, 2.93415158, 0.        ]) v_inf_a = array([ 0.13741897,  2.67390837, -0.        ])
8.894504559102828
Vd = array([ 0.61840124, 32.71890603,  0.        ]) Va = array([ -3.88091916, -21.12650895,  -0.        ])
v_inf_d = array([0.61840124, 2.93582215, 0.        ]) v_inf_a = array([ 0.12377786,  2.66919084, -0.        ])
8.99474498243568
Vd = array([ 0.55308335, 32.72040716,  0.        ]) Va = array([ -3.47616759, -21.19737925,  -0.        ])
v_inf_d = array([0.55308335, 2.93732328, 0.        ]) v_inf_a = array([ 0.11030061,  2.66493775, -0.        ])
9.095551421770214
Vd = array([ 0.48783925, 32.72173952,  0.        ]) Va = array([ -3.07016266, -21.26043292,  -0.        ])
v_inf_d = array([0.48783925, 2.93865563, 0.        ]) v_inf_a = array([ 0.09697201,  2.66115116, -0.        ])
9.1969244669838
Vd = array([ 0.42266245, 32.72290372,  0.        ]) Va = array([ -2.66304877, -21.31564977,  -0.        ])
v_inf_d = array([0.42266245, 2.93981984, 0.        ]) v_inf_a = array([ 0.08377681,  2.657833  , -0.        ])
9.298862464089702
Vd = array([ 0.35754154, 32.72390049,  0.        ]) Va = array([ -2.25497551, -21.36301166,  -0.        ])

In [75]:
delta_vs_shaped = np.reshape(delta_vs, (-1, 3))
df = pd.DataFrame(delta_vs_shaped)
with pd.ExcelWriter("deltaVs.xlsx") as writer:
    df.to_excel(writer, sheet_name="Sheet_name_1")

In [78]:
df

            0         1         2
0    5.463433  3.531044  8.994477
1    5.404350  3.488497  8.892848
2    5.346916  3.447016  8.793932
3    5.291078  3.406569  8.697646
4    5.236786  3.367128  8.603914
..        ...       ...       ...
175  5.236785  3.367128  8.603914
176  5.291079  3.406568  8.697646
177  5.346917  3.447015  8.793932
178  5.404351  3.488497  8.892848
179  5.463435  3.531042  8.994477

[180 rows x 3 columns]

In [79]:
df.columns = ["LEO", "LMO", "TOTAL"]

In [80]:
with pd.ExcelWriter("deltaVs.xlsx") as writer:
    df.to_excel(writer, sheet_name="Sheet_name_1")

## Given Time of Flight

In [ ]:
initial_guess = 160

def wrapped_simulate(x, t_of_f):
    anomaly = x
    deltaV_LEO, deltaV_LMO, delta_total = simulate(anomaly, t_of_f)
    return delta_total

optimized = minimize(wrapped_simulate,initial_guess, args=259, method = "Nelder-Mead", bounds=[(130,240)])
print(f"{optimized.x[0] = }")

[160.]
8.932641912597093
Vd = array([ 3.68253107, 32.44026584,  0.        ]) Va = array([ -5.6695144 , -20.59781958,  -0.        ])
v_inf_d = array([3.68253107, 2.65718196, 0.        ]) v_inf_a = array([ 2.58354524,  2.07727542, -0.        ])
4.078017629394747 2.4488242392463224 6.526841868641069
[168.]
9.279668759929645
Vd = array([ 2.16265344, 32.62671449,  0.        ]) Va = array([ -3.48990287, -21.1537663 ,  -0.        ])
v_inf_d = array([2.16265344, 2.84363061, 0.        ]) v_inf_a = array([ 1.52707528,  2.44926014, -0.        ])
3.737561749579804 2.2189938939226304 5.956555643502434
[176.]
9.666513218966049
Vd = array([ 0.71160198, 32.71554582,  0.        ]) Va = array([ -1.17973832, -21.44535417,  -0.        ])
v_inf_d = array([0.71160198, 2.93246194, 0.        ]) v_inf_a = array([ 0.50350855,  2.62619764, -0.        ])
3.5755735579549572 2.1139225358324945 5.689496093787452
[184.]
10.09586629563254
Vd = array([-0.66765765, 32.71647208, -0.        ]) Va = array([  1.22362911, -21.44289454,   0.        ])
v_inf_d = array([-0.66765765,  2.93338819, -0.        ]) v_inf_a = array([-0.45961777,  2.62865728,  0.        ])
3.573111924516585 2.1112849417601733 5.684396866276758
[200.]
11.092688163888873
Vd = array([-3.20705848, 32.49063585, -0.        ]) Va = array([  6.13048857, -20.465225  ,   0.        ])
v_inf_d = array([-3.20705848,  2.70755197, -0.        ]) v_inf_a = array([-2.12257107,  2.20987   ,  0.        ])
3.9489850421133745 2.3115420180008135 6.260527060114188
[176.]
9.666513218966049
Vd = array([ 0.71160198, 32.71554582,  0.        ]) Va = array([ -1.17973832, -21.44535417,  -0.        ])
v_inf_d = array([0.71160198, 2.93246194, 0.        ]) v_inf_a = array([ 0.50350855,  2.62619764, -0.        ])
3.5755735579549572 2.1139225358324945 5.689496093787452
[192.]
10.570386755672946
Vd = array([-1.97381046, 32.63867632, -0.        ]) Va = array([  3.67667423, -21.12209432,   0.        ])
v_inf_d = array([-1.97381046,  2.85559244, -0.        ]) v_inf_a = array([-1.34030392,  2.48093211,  0.        ])
3.7061672297423485 2.185436234572218 5.891603464314566

TypeError: cannot unpack non-iterable numpy.float64 object

In [132]:
wrapped_simulate(1,160)

1
4.015343851784693
Vd = array([26.8133971,  0.4152297,  0.       ]) Va = array([-10.46920653,   0.08986935,   0.        ])
v_inf_d = array([ 26.8133971 , -29.36785418,   0.        ]) v_inf_a = array([-10.04807417, -24.03678757,   0.        ])

np.float64(56.62806024639516)

In [136]:
result = []

for t_of_f in range(200,400, 1):
    try:
        optimized = minimize(wrapped_simulate,initial_guess, args=t_of_f, method = "Nelder-Mead", bounds=[(0,359)])
        result.append(t_of_f)
        result.append(optimized.x[0])
    
    except:
        print(f"{t_of_f} not valid")

[160.]
6.449572874401607
Vd = array([-2.23507406, 33.07278698,  0.        ]) Va = array([-11.4082605 , -18.95093849,  -0.        ])
v_inf_d = array([-2.23507406,  3.2897031 ,  0.        ]) v_inf_a = array([-3.15520086,  3.72415651, -0.        ])
[168.]
6.720452352080005
Vd = array([-3.82250818, 33.00797232,  0.        ]) Va = array([ -9.40977477, -20.15131824,  -0.        ])
v_inf_d = array([-3.82250818,  3.22488844,  0.        ]) v_inf_a = array([-4.39279662,  3.45170819, -0.        ])
[152.]
6.216644120718839
Vd = array([-0.54862208, 33.02322213,  0.        ]) Va = array([-13.15903114, -17.55436607,  -0.        ])
v_inf_d = array([-0.54862208,  3.24013825,  0.        ]) v_inf_a = array([-1.83052642,  3.75145256, -0.        ])
[144.]
6.018174913120597
Vd = array([ 1.23017266, 32.84492844,  0.        ]) Va = array([-14.64394864, -16.01059335,  -0.        ])
v_inf_d = array([1.23017266, 3.06184456, 0.        ]) v_inf_a = array([-0.46049531,  3.51125539, -0.        ])
[128.]
5.7109108596567975
Vd = array([ 5.0243165 , 32.04481784,  0.        ]) Va = array([-16.78859645, -12.67828138,  -0.        ])
v_inf_d = array([5.0243165 , 2.26173396, 0.        ]) v_inf_a = array([ 2.22636473,  2.17783448, -0.        ])
[136.]
5.850718523025025
Vd = array([ 3.09190211, 32.5234763 ,  0.        ]) Va = array([-15.8539282 , -14.36909922,  -0.        ])
v_inf_d = array([3.09190211, 2.74039242, 0.        ]) v_inf_a = array([ 0.90840897,  2.98880905, -0.        ])
[152.]
6.216644120718839
Vd = array([-0.54862208, 33.02322213,  0.        ]) Va = array([-13.15903114, -17.55436607,  -0.        ])
v_inf_d = array([-0.54862208,  3.24013825,  0.        ]) v_inf_a = array([-1.83052642,  3.75145256, -0.        ])
[140.]
5.930782755503034
Vd = array([ 2.15136889, 32.70298988,  0.        ]) Va = array([-15.28352731, -15.19899374,  -0.        ])
v_inf_d = array([2.15136889, 2.919906  , 0.        ]) v_inf_a = array([ 0.22715117,  3.28591307, -0.        ])
[136.]
5.850718523025025
Vd = array([ 3.09190211, 32.5234763 ,  0.        ]) Va = array([-15.8539282 , -14.36909922,  -0.        ])
v_inf_d = array([3.09190211, 2.74039242, 0.        ]) v_inf_a = array([ 0.90840897,  2.98880905, -0.        ])
[142.]
5.973536479804193
Vd = array([ 1.68825937, 32.77854555,  0.        ]) Va = array([-14.97237866, -15.60746064,  -0.        ])
v_inf_d = array([1.68825937, 2.99546167, 0.        ]) v_inf_a = array([-0.11626281,  3.40750054, -0.        ])
[138.]
5.889860913011848
Vd = array([ 2.61931547, 32.61803985,  0.        ]) Va = array([-15.57737324, -14.78595491,  -0.        ])
v_inf_d = array([2.61931547, 2.83495597, 0.        ]) v_inf_a = array([ 0.5689705 ,  3.14637652, -0.        ])
[141.]
5.95192733962015
Vd = array([ 1.91919762, 32.74192821,  0.        ]) Va = array([-15.13011527, -15.40384617,  -0.        ])
v_inf_d = array([1.91919762, 2.95884433, 0.        ]) v_inf_a = array([ 0.05559475,  3.34894396, -0.        ])
[142.]
5.973536479804193
Vd = array([ 1.68825937, 32.77854555,  0.        ]) Va = array([-14.97237866, -15.60746064,  -0.        ])
v_inf_d = array([1.68825937, 2.99546167, 0.        ]) v_inf_a = array([-0.11626281,  3.40750054, -0.        ])
[140.5]
5.941297390612196
Vd = array([ 2.03513059, 32.7227509 ,  0.        ]) Va = array([-15.20736202, -15.30156874,  -0.        ])
v_inf_d = array([2.03513059, 2.93966702, 0.        ]) v_inf_a = array([ 0.14141667,  3.3179887 , -0.        ])
[140.]
5.930782755503034
Vd = array([ 2.15136889, 32.70298988,  0.        ]) Va = array([-15.28352731, -15.19899374,  -0.        ])
v_inf_d = array([2.15136889, 2.919906  , 0.        ]) v_inf_a = array([ 0.22715117,  3.28591307, -0.        ])
[140.75]
5.9465978993672834
Vd = array([ 1.97712575, 32.73241231,  0.        ]) Va = array([-15.16887381, -15.3527454 ,  -0.        ])
v_inf_d = array([1.97712575, 2.94932842, 0.        ]) v_inf_a = array([ 0.09851588,  3.33360627, -0.        ])
[140.25]
5.9360257103080825
Vd = array([ 2.09321175, 32.71294357,  0.        ]) Va = array([-15.24557986, -15.25031769,  -0.        ])
v_inf_d = array([2.09321175, 2.92985969, 0.        ]) v_inf_a = array([ 0.18429561,  3.30209104, -0.        ])
[140.625]
5.943944034995156
Vd = array([ 2.0061186 , 32.72759982,  0.        ]) Va = array([-15.18815171, -15.32716646,  -0.        ])
v_inf_d = array([2.0061186 , 2.94451594, 0.        ]) v_inf_a = array([ 0.11996891,  3.32583249, -0.        ])
[140.375]
5.938657953340496
Vd = array([ 2.06416165, 32.71786551,  0.        ]) Va = array([-15.22650473, -15.27595243,  -0.        ])
v_inf_d = array([2.06416165, 2.93478162, 0.        ]) v_inf_a = array([ 0.16285897,  3.31007489, -0.        ])
[140.5625]
5.942619811110033
Vd = array([ 2.02062221, 32.72517992,  0.        ]) Va = array([-15.19776531, -15.31436994,  -0.        ])
v_inf_d = array([2.02062221, 2.94209603, 0.        ]) v_inf_a = array([ 0.13069347,  3.32191935, -0.        ])
[140.4375]
5.939976771892081
Vd = array([ 2.04964374, 32.72031277,  0.        ]) Va = array([-15.21694182, -15.2887629 ,  -0.        ])
v_inf_d = array([2.04964374, 2.93722888, 0.        ]) v_inf_a = array([ 0.15213852,  3.31404055, -0.        ])
[140.53125]
5.941958375538309
Vd = array([ 2.0278758 , 32.72396655,  0.        ]) Va = array([-15.20256577, -15.30796992,  -0.        ])
v_inf_d = array([2.0278758 , 2.94088267, 0.        ]) v_inf_a = array([ 0.13605524,  3.31995621, -0.        ])
[140.5625]
5.942619811110033
Vd = array([ 2.02062221, 32.72517992,  0.        ]) Va = array([-15.19776531, -15.31436994,  -0.        ])
v_inf_d = array([2.02062221, 2.94209603, 0.        ]) v_inf_a = array([ 0.13069347,  3.32191935, -0.        ])
[140.515625]
5.941627826757128
Vd = array([ 2.03150304, 32.72335901,  0.        ]) Va = array([-15.20496442, -15.30476948,  -0.        ])
v_inf_d = array([2.03150304, 2.94027513, 0.        ]) v_inf_a = array([ 0.138736,  3.318973, -0.      ])
[140.5]
5.941297390612196
Vd = array([ 2.03513059, 32.7227509 ,  0.        ]) Va = array([-15.20736202, -15.30156874,  -0.        ])
v_inf_d = array([2.03513059, 2.93966702, 0.        ]) v_inf_a = array([ 0.14141667,  3.3179887 , -0.        ])
[140.5234375]
5.941793087066616
Vd = array([ 2.02968938, 32.72366285,  0.        ]) Va = array([-15.20376523, -15.30636974,  -0.        ])
v_inf_d = array([2.02968938, 2.94057897, 0.        ]) v_inf_a = array([ 0.13739563,  3.31946474, -0.        ])
[140.53125]
5.941958375538309
Vd = array([ 2.0278758 , 32.72396655,  0.        ]) Va = array([-15.20256577, -15.30796992,  -0.        ])
v_inf_d = array([2.0278758 , 2.94088267, 0.        ]) v_inf_a = array([ 0.13605524,  3.31995621, -0.        ])
[140.51953125]
5.941710453391794
Vd = array([ 2.0305962 , 32.72351095,  0.        ]) Va = array([-15.20436486, -15.30556962,  -0.        ])
v_inf_d = array([2.0305962 , 2.94042707, 0.        ]) v_inf_a = array([ 0.13806582,  3.31921891, -0.        ])
[140.52734375]
5.941875727781993
Vd = array([ 2.02878258, 32.72381472,  0.        ]) Va = array([-15.20316554, -15.30716984,  -0.        ])
v_inf_d = array([2.02878258, 2.94073084, 0.        ]) v_inf_a = array([ 0.13672544,  3.31971051, -0.        ])
[140.52148438]
5.94175176934916
Vd = array([ 2.03014279, 32.7235869 ,  0.        ]) Va = array([-15.20406505, -15.30596968,  -0.        ])
v_inf_d = array([2.03014279, 2.94050302, 0.        ]) v_inf_a = array([ 0.13773072,  3.31934184, -0.        ])
[140.52539062]
5.9418344065442135
Vd = array([ 2.02923598, 32.72373879,  0.        ]) Va = array([-15.20346539, -15.30676979,  -0.        ])
v_inf_d = array([2.02923598, 2.94065491, 0.        ]) v_inf_a = array([ 0.13706053,  3.31958764, -0.        ])
[140.52246094]
5.941772427987872
Vd = array([ 2.02991609, 32.72362488,  0.        ]) Va = array([-15.20391514, -15.30616971,  -0.        ])
v_inf_d = array([2.02991609, 2.940541  , 0.        ]) v_inf_a = array([ 0.13756318,  3.31940329, -0.        ])
[140.52148438]
5.94175176934916
Vd = array([ 2.03014279, 32.7235869 ,  0.        ]) Va = array([-15.20406505, -15.30596968,  -0.        ])
v_inf_d = array([2.03014279, 2.94050302, 0.        ]) v_inf_a = array([ 0.13773072,  3.31934184, -0.        ])
[140.52294922]
5.9417827574722395
Vd = array([ 2.02980274, 32.72364387,  0.        ]) Va = array([-15.20384019, -15.30626972,  -0.        ])
v_inf_d = array([2.02980274, 2.94055998, 0.        ]) v_inf_a = array([ 0.1374794 ,  3.31943402, -0.        ])
[140.52197266]
5.941762098613516
Vd = array([ 2.03002944, 32.72360589,  0.        ]) Va = array([-15.2039901 , -15.30606969,  -0.        ])
v_inf_d = array([2.03002944, 2.94052201, 0.        ]) v_inf_a = array([ 0.13764695,  3.31937256, -0.        ])
[140.52270508]
5.941777592716308
Vd = array([ 2.02985941, 32.72363437,  0.        ]) Va = array([-15.20387767, -15.30621972,  -0.        ])
v_inf_d = array([2.02985941, 2.94055049, 0.        ]) v_inf_a = array([ 0.13752129,  3.31941866, -0.        ])
[140.5222168]
5.941767263286941
Vd = array([ 2.02997276, 32.72361539,  0.        ]) Va = array([-15.20395262, -15.3061197 ,  -0.        ])
v_inf_d = array([2.02997276, 2.9405315 , 0.        ]) v_inf_a = array([ 0.13760506,  3.31938793, -0.        ])
[140.52258301]
5.9417750103486515
Vd = array([ 2.02988775, 32.72362963,  0.        ]) Va = array([-15.20389641, -15.30619471,  -0.        ])
v_inf_d = array([2.02988775, 2.94054574, 0.        ]) v_inf_a = array([ 0.13754223,  3.31941097, -0.        ])
[140.52270508]
5.941777592716308
Vd = array([ 2.02985941, 32.72363437,  0.        ]) Va = array([-15.20387767, -15.30621972,  -0.        ])
v_inf_d = array([2.02985941, 2.94055049, 0.        ]) v_inf_a = array([ 0.13752129,  3.31941866, -0.        ])
[140.52252197]
5.941773719167402
Vd = array([ 2.02990192, 32.72362725,  0.        ]) Va = array([-15.20390577, -15.30618221,  -0.        ])
v_inf_d = array([2.02990192, 2.94054337, 0.        ]) v_inf_a = array([ 0.13755271,  3.31940713, -0.        ])
[160.]
6.498954640550547
Vd = array([-2.10802508, 33.05907836,  0.        ]) Va = array([-11.28501537, -18.98621981,  -0.        ])
v_inf_d = array([-2.10802508,  3.27599448,  0.        ]) v_inf_a = array([-3.03195573,  3.68887519, -0.        ])
[168.]
6.771635985864031
Vd = array([-3.69398367, 32.99973879,  0.        ]) Va = array([ -9.2826443 , -20.17281519,  -0.        ])
v_inf_d = array([-3.69398367,  3.2166549 ,  0.        ]) v_inf_a = array([-4.26566615,  3.43021125, -0.        ])
[152.]
6.264220990386746
Vd = array([-0.42382296, 33.00414898,  0.        ]) Va = array([-13.04151959, -17.60266811,  -0.        ])
v_inf_d = array([-0.42382296,  3.22106509,  0.        ]) v_inf_a = array([-1.71301487,  3.70315052, -0.        ])
[144.]
6.063961105954123
Vd = array([ 1.35194236, 32.8206988 ,  0.        ]) Va = array([-14.53389789, -16.07089022,  -0.        ])
v_inf_d = array([1.35194236, 3.03761492, 0.        ]) v_inf_a = array([-0.35044455,  3.45095852, -0.        ])
[128.]
5.753224305648855
Vd = array([ 5.13776236, 32.01132585,  0.        ]) Va = array([-16.69797244, -12.75856511,  -0.        ])
v_inf_d = array([5.13776236, 2.22824197, 0.        ]) v_inf_a = array([ 2.31698873,  2.09755075, -0.        ])
[136.]
5.894744981109135
Vd = array([ 3.20987608, 32.49440375,  0.        ]) Va = array([-15.75290496, -14.44012629,  -0.        ])
v_inf_d = array([3.20987608, 2.71131987, 0.        ]) v_inf_a = array([ 1.00943221,  2.91778198, -0.        ])
[152.]
6.264220990386746
Vd = array([-0.42382296, 33.00414898,  0.        ]) Va = array([-13.04151959, -17.60266811,  -0.        ])
v_inf_d = array([-0.42382296,  3.22106509,  0.        ]) v_inf_a = array([-1.71301487,  3.70315052, -0.        ])
[140.]
5.975684200194591
Vd = array([ 2.2713349 , 32.67629278,  0.        ]) Va = array([-15.17780592, -15.2648276 ,  -0.        ])
v_inf_d = array([2.2713349 , 2.89320889, 0.        ]) v_inf_a = array([ 0.33287257,  3.22007921, -0.        ])
[136.]
5.894744981109135
Vd = array([ 3.20987608, 32.49440375,  0.        ]) Va = array([-15.75290496, -14.44012629,  -0.        ])
v_inf_d = array([3.20987608, 2.71131987, 0.        ]) v_inf_a = array([ 1.00943221,  2.91778198, -0.        ])
[142.]
6.018879202540191
Vd = array([ 1.80915102, 32.75307154,  0.        ]) Va = array([-14.86444498, -15.67056733,  -0.        ])
v_inf_d = array([1.80915102, 2.96998765, 0.        ]) v_inf_a = array([-0.00832912,  3.34439385, -0.        ])
[144.]
6.063961105954123
Vd = array([ 1.35194236, 32.8206988 ,  0.        ]) Va = array([-14.53389789, -16.07089022,  -0.        ])
v_inf_d = array([1.35194236, 3.03761492, 0.        ]) v_inf_a = array([-0.35044455,  3.45095852, -0.        ])
[141.]
5.997049133636301
Vd = array([ 2.03963237, 32.71583989,  0.        ]) Va = array([-15.02327602, -15.46832699,  -0.        ])
v_inf_d = array([2.03963237, 2.932756  , 0.        ]) v_inf_a = array([ 0.16243401,  3.28446314, -0.        ])
[140.]
5.975684200194591
Vd = array([ 2.2713349 , 32.67629278,  0.        ]) Va = array([-15.17780592, -15.2648276 ,  -0.        ])
v_inf_d = array([2.2713349 , 2.89320889, 0.        ]) v_inf_a = array([ 0.33287257,  3.22007921, -0.        ])
[141.5]
6.007905615177153
Vd = array([ 1.92423761, 32.73474343,  0.        ]) Va = array([-14.94439793, -15.56961047,  -0.        ])
v_inf_d = array([1.92423761, 2.95165954, 0.        ]) v_inf_a = array([ 0.07708698,  3.31498425, -0.        ])
[140.5]
5.986308935594611
Vd = array([ 2.15533244, 32.69635748,  0.        ]) Va = array([-15.10107878, -15.36672875,  -0.        ])
v_inf_d = array([2.15533244, 2.9132736 , 0.        ]) v_inf_a = array([ 0.24769991,  3.2528287 , -0.        ])
[141.25]
6.002462787608078
Vd = array([ 1.98189665, 32.7253638 ,  0.        ]) Va = array([-14.98397137, -15.51900881,  -0.        ])
v_inf_d = array([1.98189665, 2.94227992, 0.        ]) v_inf_a = array([ 0.11976988,  3.29986275, -0.        ])
[141.5]
6.007905615177153
Vd = array([ 1.92423761, 32.73474343,  0.        ]) Va = array([-14.94439793, -15.56961047,  -0.        ])
v_inf_d = array([1.92423761, 2.95165954, 0.        ]) v_inf_a = array([ 0.07708698,  3.31498425, -0.        ])
[141.125]
5.999752320347092
Vd = array([ 2.01075495, 32.72061991,  0.        ]) Va = array([-15.00365729, -15.49367783,  -0.        ])
v_inf_d = array([2.01075495, 2.93753602, 0.        ]) v_inf_a = array([ 0.14110439,  3.29219773, -0.        ])
[141.375]
6.005180548267814
Vd = array([ 1.95305752, 32.73007162,  0.        ]) Va = array([-14.96421824, -15.54431976,  -0.        ])
v_inf_d = array([1.95305752, 2.94698774, 0.        ]) v_inf_a = array([ 0.09843068,  3.30745825, -0.        ])
[141.1875]
6.001106643105432
Vd = array([ 1.9963234 , 32.72299637,  0.        ]) Va = array([-14.99382273, -15.50634582,  -0.        ])
v_inf_d = array([1.9963234 , 2.93991248, 0.        ]) v_inf_a = array([ 0.13043773,  3.29603893, -0.        ])
[141.125]
5.999752320347092
Vd = array([ 2.01075495, 32.72061991,  0.        ]) Va = array([-15.00365729, -15.49367783,  -0.        ])
v_inf_d = array([2.01075495, 2.93753602, 0.        ]) v_inf_a = array([ 0.14110439,  3.29219773, -0.        ])
[141.21875]
6.001784487538462
Vd = array([ 1.98910943, 32.72418121,  0.        ]) Va = array([-14.98889915, -15.51267794,  -0.        ])
v_inf_d = array([1.98910943, 2.94109733, 0.        ]) v_inf_a = array([ 0.12510395,  3.29795302, -0.        ])
[141.25]
6.002462787608078
Vd = array([ 1.98189665, 32.7253638 ,  0.        ]) Va = array([-14.98397137, -15.51900881,  -0.        ])
v_inf_d = array([1.98189665, 2.94227992, 0.        ]) v_inf_a = array([ 0.11976988,  3.29986275, -0.        ])
[141.203125]
6.001445508379921
Vd = array([ 1.99271627, 32.72358907,  0.        ]) Va = array([-14.99136146, -15.50951203,  -0.        ])
v_inf_d = array([1.99271627, 2.94050519, 0.        ]) v_inf_a = array([ 0.12777088,  3.29699652, -0.        ])
[141.234375]
6.002123580606145
Vd = array([ 1.98550289, 32.72477279,  0.        ]) Va = array([-14.98643578, -15.51584353,  -0.        ])
v_inf_d = array([1.98550289, 2.9416889 , 0.        ]) v_inf_a = array([ 0.12243695,  3.29890843, -0.        ])
[141.2109375]
6.001614983722108
Vd = array([ 1.99091281, 32.72388521,  0.        ]) Va = array([-14.99013044, -15.51109503,  -0.        ])
v_inf_d = array([1.99091281, 2.94080133, 0.        ]) v_inf_a = array([ 0.12643743,  3.2974749 , -0.        ])
[141.2265625]
6.001954019832089
Vd = array([ 1.98730612, 32.72447707,  0.        ]) Va = array([-14.9876676 , -15.51426078,  -0.        ])
v_inf_d = array([1.98730612, 2.94139319, 0.        ]) v_inf_a = array([ 0.12377046,  3.29843086, -0.        ])
[141.21484375]
6.001699732070819
Vd = array([ 1.99001111, 32.72403323,  0.        ]) Va = array([-14.98951482, -15.51188649,  -0.        ])
v_inf_d = array([1.99001111, 2.94094935, 0.        ]) v_inf_a = array([ 0.12577069,  3.29771399, -0.        ])
[141.2109375]
6.001614983722108
Vd = array([ 1.99091281, 32.72388521,  0.        ]) Va = array([-14.99013044, -15.51109503,  -0.        ])
v_inf_d = array([1.99091281, 2.94080133, 0.        ]) v_inf_a = array([ 0.12643743,  3.2974749 , -0.        ])
[141.21679688]
6.001742108914748
Vd = array([ 1.98956027, 32.72410722,  0.        ]) Va = array([-14.98920699, -15.51228222,  -0.        ])
v_inf_d = array([1.98956027, 2.94102334, 0.        ]) v_inf_a = array([ 0.12543732,  3.29783351, -0.        ])
[141.21289062]
6.001657357006625
Vd = array([ 1.99046196, 32.72395922,  0.        ]) Va = array([-14.98982264, -15.51149076,  -0.        ])
v_inf_d = array([1.99046196, 2.94087534, 0.        ]) v_inf_a = array([ 0.12610406,  3.29759446, -0.        ])
[141.21582031]
6.001720920270318
Vd = array([ 1.98978569, 32.72407023,  0.        ]) Va = array([-14.98936091, -15.51208436,  -0.        ])
v_inf_d = array([1.98978569, 2.94098634, 0.        ]) v_inf_a = array([ 0.12560401,  3.29777376, -0.        ])
[141.21679688]
6.001742108914748
Vd = array([ 1.98956027, 32.72410722,  0.        ]) Va = array([-14.98920699, -15.51228222,  -0.        ])
v_inf_d = array([1.98956027, 2.94102334, 0.        ]) v_inf_a = array([ 0.12543732,  3.29783351, -0.        ])
[141.21533203]
6.001710326114953
Vd = array([ 1.9898984 , 32.72405173,  0.        ]) Va = array([-14.98943787, -15.51198542,  -0.        ])
v_inf_d = array([1.9898984 , 2.94096784, 0.        ]) v_inf_a = array([ 0.12568735,  3.29774388, -0.        ])
[141.21484375]
6.001699732070819
Vd = array([ 1.99001111, 32.72403323,  0.        ]) Va = array([-14.98951482, -15.51188649,  -0.        ])
v_inf_d = array([1.99001111, 2.94094935, 0.        ]) v_inf_a = array([ 0.12577069,  3.29771399, -0.        ])
[141.21557617]
6.001715623178726
Vd = array([ 1.98984204, 32.72406098,  0.        ]) Va = array([-14.98939939, -15.51203489,  -0.        ])
v_inf_d = array([1.98984204, 2.94097709, 0.        ]) v_inf_a = array([ 0.12564568,  3.29775882, -0.        ])
[141.21508789]
6.001705029078983
Vd = array([ 1.98995475, 32.72404248,  0.        ]) Va = array([-14.98947635, -15.51193596,  -0.        ])
v_inf_d = array([1.98995475, 2.9409586 , 0.        ]) v_inf_a = array([ 0.12572902,  3.29772893, -0.        ])
[141.2154541]
6.001712974643363
Vd = array([ 1.98987022, 32.72405635,  0.        ]) Va = array([-14.98941863, -15.51201016,  -0.        ])
v_inf_d = array([1.98987022, 2.94097247, 0.        ]) v_inf_a = array([ 0.12566652,  3.29775135, -0.        ])
[141.21520996]
6.0017076775934886
Vd = array([ 1.98992658, 32.7240471 ,  0.        ]) Va = array([-14.98945711, -15.51196069,  -0.        ])
v_inf_d = array([1.98992658, 2.94096322, 0.        ]) v_inf_a = array([ 0.12570819,  3.2977364 , -0.        ])
[141.21539307]
6.001711650378288
Vd = array([ 1.98988431, 32.72405404,  0.        ]) Va = array([-14.98942825, -15.51199779,  -0.        ])
v_inf_d = array([1.98988431, 2.94097016, 0.        ]) v_inf_a = array([ 0.12567693,  3.29774761, -0.        ])
[160.]
6.548034460237968
Vd = array([-1.98214916, 33.04550188,  0.        ]) Va = array([-11.16290974, -19.02117868,  -0.        ])

In [138]:
result_shaped = np.reshape(result, (-1, 2))
result_shaped
df = pd.DataFrame(result_shaped)
df.columns = ["time of flight", "anomaly"]
with pd.ExcelWriter("output.xlsx") as writer:
    df.to_excel(writer, sheet_name="Sheet_name_1")

In [142]:
delta_vs = []
for index, row in df.iterrows():
    res = simulate(row["anomaly"], row["time of flight"])
    delta_vs.append(res)

140.52252197265625
5.941773719167402
Vd = array([ 2.02990192, 32.72362725,  0.        ]) Va = array([-15.20390577, -15.30618221,  -0.        ])
v_inf_d = array([2.02990192, 2.94054337, 0.        ]) v_inf_a = array([ 0.13755271,  3.31940713, -0.        ])
141.21533203125
6.001710326114953
Vd = array([ 1.9898984 , 32.72405173,  0.        ]) Va = array([-14.98943787, -15.51198542,  -0.        ])
v_inf_d = array([1.9898984 , 2.94096784, 0.        ]) v_inf_a = array([ 0.12568735,  3.29774388, -0.        ])
141.90789794921875
6.061919412395191
Vd = array([ 1.95006809, 32.72446185,  0.        ]) Va = array([-14.77241906, -15.71465832,  -0.        ])
v_inf_d = array([1.95006809, 2.94137796, 0.        ]) v_inf_a = array([ 0.11424383,  3.27639733, -0.        ])
142.60009765625
6.122397729220296
Vd = array([ 1.91043442, 32.72485342,  0.        ]) Va = array([-14.55291378, -15.91415012,  -0.        ])
v_inf_d = array([1.91043442, 2.94176954, 0.        ]) v_inf_a = array([ 0.10323426,  3.25536347, -0.        ])
143.29205322265625
6.183147456168036
Vd = array([ 1.87096483, 32.72523127,  0.        ]) Va = array([-14.33094717, -16.11045953,  -0.        ])
v_inf_d = array([1.87096483, 2.94214738, 0.        ]) v_inf_a = array([ 0.09262935,  3.2346527 , -0.        ])
143.983642578125
6.244165208723097
Vd = array([ 1.83168256, 32.72559139,  0.        ]) Va = array([-14.10658502, -16.30353748,  -0.        ])
v_inf_d = array([1.83168256, 2.94250751, 0.        ]) v_inf_a = array([ 0.08244105,  3.21426122, -0.        ])
144.67486572265625
6.305450315459865
Vd = array([ 1.7925829 , 32.72593429,  0.        ]) Va = array([-13.87987354, -16.49335993,  -0.        ])
v_inf_d = array([1.7925829 , 2.94285041, 0.        ]) v_inf_a = array([ 0.07266063,  3.1941924 , -0.        ])
145.36578369140625
6.367003627449376
Vd = array([ 1.75364758, 32.72626242,  0.        ]) Va = array([-13.65084806, -16.67991491,  -0.        ])
v_inf_d = array([1.75364758, 2.94317854, 0.        ]) v_inf_a = array([ 0.0632693 ,  3.17445266, -0.        ])
146.0562744140625
6.428821455135024
Vd = array([ 1.71489937, 32.72657223,  0.        ]) Va = array([-13.41957701, -16.86315644,  -0.        ])
v_inf_d = array([1.71489937, 2.94348835, 0.        ]) v_inf_a = array([ 0.05427861,  3.15503882, -0.        ])
146.746337890625
6.490903021615719
Vd = array([ 1.67633351, 32.72686434,  0.        ]) Va = array([-13.18610777, -17.04306274,  -0.        ])
v_inf_d = array([1.67633351, 2.94378045, 0.        ]) v_inf_a = array([ 0.04567972,  3.13595425, -0.        ])
147.43597412109375
6.553247548150378
Vd = array([ 1.63794534, 32.7271393 ,  0.        ]) Va = array([-12.95048785, -17.2196126 ,  -0.        ])
v_inf_d = array([1.63794534, 2.94405541, 0.        ]) v_inf_a = array([ 0.03746386,  3.11720222, -0.        ])
148.12518310546875
6.615854254228305
Vd = array([ 1.59973026, 32.72739767,  0.        ]) Va = array([-12.71276487, -17.39278547,  -0.        ])
v_inf_d = array([1.59973026, 2.94431378, 0.        ]) v_inf_a = array([ 0.02962225,  3.0987859 , -0.        ])
148.81396484375
6.678722357637296
Vd = array([ 1.56168373, 32.72763996,  0.        ]) Va = array([-12.47298656, -17.56256138,  -0.        ])
v_inf_d = array([1.56168373, 2.94455608, 0.        ]) v_inf_a = array([ 0.02214614,  3.08070836, -0.        ])
149.502197265625
6.7418476222358565
Vd = array([ 1.52382763, 32.7278634 ,  0.        ]) Va = array([-12.23122557, -17.72890004,  -0.        ])
v_inf_d = array([1.52382763, 2.94477951, 0.        ]) v_inf_a = array([ 0.01504633,  3.06296739, -0.        ])
150.18988037109375
6.8052290596591005
Vd = array([ 1.48615711, 32.72806874,  0.        ]) Va = array([-11.98753109, -17.89178379,  -0.        ])
v_inf_d = array([1.48615711, 2.94498486, 0.        ]) v_inf_a = array([ 0.00831379,  3.04556639, -0.        ])
150.8770751953125
6.8688674733670245
Vd = array([ 1.44865436, 32.72825829,  0.        ]) Va = array([-11.74193958, -18.05120571,  -0.        ])
v_inf_d = array([1.44865436, 2.94517441, 0.        ]) v_inf_a = array([ 1.92986724e-03,  3.02851101e+00, -0.00000000e+00])
151.563720703125
6.93276014505818
Vd = array([ 1.41132784, 32.72843112,  0.        ]) Va = array([-11.49451276, -18.20713895,  -0.        ])
v_inf_d = array([1.41132784, 2.94534724, 0.        ]) v_inf_a = array([-0.00410465,  3.01180184, -0.        ])
152.249755859375
6.996904219098759
Vd = array([ 1.3741858 , 32.72858646,  0.        ]) Va = array([-11.24531319, -18.35955806,  -0.        ])
v_inf_d = array([1.3741858 , 2.94550258, 0.        ]) v_inf_a = array([-0.00978919,  2.99543965, -0.        ])
152.93511962890625
7.061296702270396
Vd = array([ 1.33723627, 32.72872371,  0.        ]) Va = array([-10.99440428, -18.50843898,  -0.        ])
v_inf_d = array([1.33723627, 2.94563983, 0.        ]) v_inf_a = array([-0.01512338,  2.97942544, -0.        ])
153.61993408203125
7.125940252380181
Vd = array([ 1.30044879, 32.7288465 ,  0.        ]) Va = array([-10.74180938, -18.65378711,  -0.        ])
v_inf_d = array([1.30044879, 2.94576261, 0.        ]) v_inf_a = array([-0.02013528,  2.96376666, -0.        ])
154.30401611328125
7.190827979368634
Vd = array([ 1.26385696, 32.72895147,  0.        ]) Va = array([-10.48761929, -18.79556125,  -0.        ])
v_inf_d = array([1.26385696, 2.94586759, 0.        ]) v_inf_a = array([-0.02480568,  2.94845995, -0.        ])
154.9874267578125
7.25596057385659
Vd = array([ 1.22744316, 32.72904088,  0.        ]) Va = array([-10.23187113, -18.93375898,  -0.        ])
v_inf_d = array([1.22744316, 2.94595699, 0.        ]) v_inf_a = array([-0.02915323,  2.9335105 , -0.        ])
155.67010498046875
7.321334797458526
Vd = array([ 1.19121519, 32.7291143 ,  0.        ]) Va = array([ -9.97462955, -19.06836029,  -0.        ])
v_inf_d = array([1.19121519, 2.94603042, 0.        ]) v_inf_a = array([-0.03317784,  2.91891932, -0.        ])
156.35198974609375
7.38694727391223
Vd = array([ 1.15518068, 32.72917146,  0.        ]) Va = array([ -9.7159599 , -19.19934666,  -0.        ])
v_inf_d = array([1.15518068, 2.94608758, 0.        ]) v_inf_a = array([-0.03687961,  2.90468762, -0.        ])
157.03314208984375
7.452798688796391
Vd = array([ 1.11932218, 32.72921449,  0.        ]) Va = array([ -9.45589907, -19.32671772,  -0.        ])
v_inf_d = array([1.11932218, 2.9461306 , 0.        ]) v_inf_a = array([-0.04027709,  2.89082015, -0.        ])
157.7135009765625
7.518885594595804
Vd = array([ 1.08364731, 32.72924312,  0.        ]) Va = array([ -9.1945126 , -19.45045672,  -0.        ])
v_inf_d = array([1.08364731, 2.94615923, 0.        ]) v_inf_a = array([-0.04337044,  2.877318  , -0.        ])
158.39300537109375
7.585204406001882
Vd = array([ 1.04816349, 32.72925721,  0.        ]) Va = array([ -8.93186658, -19.57054844,  -0.        ])
v_inf_d = array([1.04816349, 2.94617333, 0.        ]) v_inf_a = array([-0.04615999,  2.86418234, -0.        ])
159.07159423828125
7.651751399940066
Vd = array([ 1.01287794, 32.72925677,  0.        ]) Va = array([ -8.66802767, -19.68697918,  -0.        ])
v_inf_d = array([1.01287794, 2.94617289, 0.        ]) v_inf_a = array([-0.04864626,  2.85141453, -0.        ])
159.74932861328125
7.718527188336713
Vd = array([ 0.97777338, 32.72924385,  0.        ]) Va = array([ -8.40303261, -19.79975173,  -0.        ])
v_inf_d = array([0.97777338, 2.94615996, 0.        ]) v_inf_a = array([-0.0508478,  2.8390189, -0.       ])
160.42608642578125
7.7855257071284285
Vd = array([ 0.94286914, 32.7292175 ,  0.        ]) Va = array([ -8.13696343, -19.908847  ,  -0.        ])
v_inf_d = array([0.94286914, 2.94613362, 0.        ]) v_inf_a = array([-0.05275631,  2.82699523, -0.        ])
161.1019287109375
7.852747532110018
Vd = array([ 0.90814801, 32.72917975,  0.        ]) Va = array([ -7.86985667, -20.01426936,  -0.        ])
v_inf_d = array([0.90814801, 2.94609586, 0.        ]) v_inf_a = array([-0.05439029,  2.81534764, -0.        ])
161.77667236328125
7.920184019936299
Vd = array([ 0.87364103, 32.72912898,  0.        ]) Va = array([ -7.60181072, -20.11599584,  -0.        ])
v_inf_d = array([0.87364103, 2.9460451 , 0.        ]) v_inf_a = array([-0.05573302,  2.8040748 , -0.        ])
162.450439453125
7.9878379813674
Vd = array([ 0.83931894, 32.7290681 ,  0.        ]) Va = array([ -7.33284649, -20.21403967,  -0.        ])
v_inf_d = array([0.83931894, 2.94598422, 0.        ]) v_inf_a = array([-0.05681184,  2.79318194, -0.        ])
163.12310791015625
8.055702871926925
Vd = array([ 0.80520051, 32.72899654,  0.        ]) Va = array([ -7.06304725, -20.30838764,  -0.        ])
v_inf_d = array([0.80520051, 2.94591266, 0.        ]) v_inf_a = array([-0.05761905,  2.78266912, -0.        ])
163.794677734375
8.123776756116953
Vd = array([ 0.77128049, 32.72891548,  0.        ]) Va = array([ -6.79246501, -20.39904123,  -0.        ])
v_inf_d = array([0.77128049, 2.94583159, 0.        ]) v_inf_a = array([-0.05816451,  2.77253885, -0.        ])
164.465087890625
8.192055223349952
Vd = array([ 0.73756545, 32.72882531,  0.        ]) Va = array([ -6.52116768, -20.48599677,  -0.        ])
v_inf_d = array([0.73756545, 2.94574143, 0.        ]) v_inf_a = array([-0.05844951,  2.76279246, -0.        ])
165.13433837890625
8.260536236090987
Vd = array([ 0.70405011, 32.72872725,  0.        ]) Va = array([ -6.24920707, -20.56925782,  -0.        ])
v_inf_d = array([0.70405011, 2.94564337, 0.        ]) v_inf_a = array([-0.05848397,  2.7534323 , -0.        ])
165.80230712890625
8.329212670962821
Vd = array([ 0.67075252, 32.72862114,  0.        ]) Va = array([ -5.97666762, -20.64881782,  -0.        ])
v_inf_d = array([0.67075252, 2.94553726, 0.        ]) v_inf_a = array([-0.0582609 ,  2.74445875, -0.        ])
166.46905517578125
8.398084864565833
Vd = array([ 0.63765563, 32.7285089 ,  0.        ]) Va = array([ -5.7035846 , -20.72468829,  -0.        ])
v_inf_d = array([0.63765563, 2.94542502, 0.        ]) v_inf_a = array([-0.05779883,  2.735875  , -0.        ])
167.13446044921875
8.467145457168929
Vd = array([ 0.60477725, 32.72839054,  0.        ]) Va = array([ -5.43004262, -20.79686568,  -0.        ])
v_inf_d = array([0.60477725, 2.94530665, 0.        ]) v_inf_a = array([-0.057091  ,  2.72768145, -0.        ])
167.798583984375
8.536394753708981
Vd = array([ 0.57210043, 32.72826788,  0.        ]) Va = array([ -5.15607628, -20.8653631 ,  -0.        ])
v_inf_d = array([0.57210043, 2.945184  , 0.        ]) v_inf_a = array([-0.05615588,  2.71988099, -0.        ])
168.46124267578125
8.605822480672604
Vd = array([ 0.53965415, 32.72814059,  0.        ]) Va = array([ -4.88178721, -20.93017556,  -0.        ])
v_inf_d = array([0.53965415, 2.94505671, 0.        ]) v_inf_a = array([-0.05497874,  2.71247333, -0.        ])
169.12249755859375
8.67542881095728
Vd = array([ 0.5074214 , 32.72801052,  0.        ]) Va = array([ -4.60720959, -20.99131848,  -0.        ])
v_inf_d = array([0.5074214 , 2.94492664, 0.        ]) v_inf_a = array([-0.0535781,  2.7054612, -0.       ])
169.78228759765625
8.745208562032595
Vd = array([ 0.47540808, 32.72787849,  0.        ]) Va = array([ -4.3324111 , -21.04879901,  -0.        ])
v_inf_d = array([0.47540808, 2.94479461, 0.        ]) v_inf_a = array([-0.05195597,  2.69884573, -0.        ])
170.4405517578125
8.815156418730739
Vd = array([ 0.44361993, 32.72774538,  0.        ]) Va = array([ -4.05745935, -21.10262595,  -0.        ])
v_inf_d = array([0.44361993, 2.94466149, 0.        ]) v_inf_a = array([-0.05011447,  2.69262807, -0.        ])
171.0972900390625
8.88526974798724
Vd = array([ 0.41205141, 32.72761251,  0.        ]) Va = array([ -3.78240445, -21.15281319,  -0.        ])
v_inf_d = array([0.41205141, 2.94452863, 0.        ]) v_inf_a = array([-0.04806389,  2.68680986, -0.        ])
171.75238037109375
8.955540224629475
Vd = array([ 0.38071929, 32.72748047,  0.        ]) Va = array([ -3.50733097, -21.19936879,  -0.        ])
v_inf_d = array([0.38071929, 2.94439659, 0.        ]) v_inf_a = array([-0.04579848,  2.68139166, -0.        ])
172.40582275390625
9.025965020904437
Vd = array([ 0.34961789, 32.72735068,  0.        ]) Va = array([ -3.23228852, -21.24230939,  -0.        ])
v_inf_d = array([0.34961789, 2.9442668 , 0.        ]) v_inf_a = array([-0.04332865,  2.67637497, -0.        ])
173.05755615234375
9.096538398612886
Vd = array([ 0.31875262, 32.72722418,  0.        ]) Va = array([ -2.9573438 , -21.28164951,  -0.        ])
v_inf_d = array([0.31875262, 2.9441403 , 0.        ]) v_inf_a = array([-0.04065686,  2.67176077, -0.        ])
173.70751953125
9.167254490284707
Vd = array([ 0.2881288 , 32.72710211,  0.        ]) Va = array([ -2.68256326, -21.31740527,  -0.        ])
v_inf_d = array([0.2881288 , 2.94401823, 0.        ]) v_inf_a = array([-0.03778567,  2.66754997, -0.        ])
186.26409912109375
10.602765397700809
Vd = array([-0.27006983, 32.7276496 , -0.        ]) Va = array([  2.68722742, -21.31742191,   0.        ])
v_inf_d = array([-0.27006983,  2.94456571, -0.        ]) v_inf_a = array([0.05433105, 2.66884048, 0.        ])
186.8658447265625
10.675098606201162
Vd = array([-0.2950348, 32.7279378, -0.       ]) Va = array([  2.94501848, -21.28411395,   0.        ])
v_inf_d = array([-0.2950348 ,  2.94485392, -0.        ]) v_inf_a = array([0.06035762, 2.67317426, 0.        ])
187.46466064453125
10.747429019549097
Vd = array([-0.31968707, 32.72826242, -0.        ]) Va = array([  3.20138188, -21.24792218,   0.        ])
v_inf_d = array([-0.31968707,  2.94517853, -0.        ]) v_inf_a = array([0.06649808, 2.67790968, 0.        ])
188.060546875
10.819752076373607
Vd = array([-0.34403238, 32.72862485, -0.        ]) Va = array([  3.45628552, -21.20889002,   0.        ])
v_inf_d = array([-0.34403238,  2.94554097, -0.        ]) v_inf_a = array([0.07274287, 2.68304515, 0.        ])
188.65350341796875
10.892063239406417
Vd = array([-0.36807637, 32.72902646, -0.        ]) Va = array([  3.70969834, -21.16706106,   0.        ])
v_inf_d = array([-0.36807637,  2.94594258, -0.        ]) v_inf_a = array([0.07908261, 2.68857886, 0.        ])
189.243408203125
10.96435048623439
Vd = array([-0.39180467, 32.72946918, -0.        ]) Va = array([  3.96155305, -21.12248667,   0.        ])
v_inf_d = array([-0.39180467,  2.9463853 , -0.        ]) v_inf_a = array([0.08552165, 2.69450951, 0.        ])
189.8302001953125
11.036605359699731
Vd = array([-0.41521297, 32.72995468, -0.        ]) Va = array([  4.21180204, -21.07521627,   0.        ])
v_inf_d = array([-0.41521297,  2.94687079, -0.        ]) v_inf_a = array([0.09205754, 2.70083538, 0.        ])
190.4139404296875
11.108826939299673
Vd = array([-0.43831669, 32.73048394, -0.        ]) Va = array([  4.46043594, -21.02529176,   0.        ])
v_inf_d = array([-0.43831669,  2.94740005, -0.        ]) v_inf_a = array([0.09867453, 2.70755392, 0.        ])
190.9945068359375
11.181002915461876
Vd = array([-0.46110148, 32.73105892, -0.        ]) Va = array([  4.70739063, -20.97276778,   0.        ])
v_inf_d = array([-0.46110148,  2.94797504, -0.        ]) v_inf_a = array([0.10537719, 2.71466346, 0.        ])
191.57183837890625
11.253124641274265
Vd = array([-0.48356293, 32.73168129, -0.        ]) Va = array([  4.95262172, -20.91769618,   0.        ])
v_inf_d = array([-0.48356293,  2.94859741, -0.        ]) v_inf_a = array([0.11216342, 2.7221619 , 0.        ])
192.1458740234375
11.325183379667097
Vd = array([-0.50569663, 32.7323527 , -0.        ]) Va = array([  5.19608592, -20.86012981,   0.        ])
v_inf_d = array([-0.50569663,  2.94926881, -0.        ]) v_inf_a = array([0.11903122, 2.73004701, 0.        ])
192.7166748046875
11.397178177147948
Vd = array([-0.52751764, 32.73307397, -0.        ]) Va = array([  5.43777809, -20.80011198,   0.        ])
v_inf_d = array([-0.52751764,  2.94999009, -0.        ]) v_inf_a = array([0.12596555, 2.73831563, 0.        ])
193.2840576171875
11.469092368925546
Vd = array([-0.54900192, 32.73384757, -0.        ]) Va = array([  5.6776201 , -20.73770701,   0.        ])
v_inf_d = array([-0.54900192,  2.95076369, -0.        ]) v_inf_a = array([0.13297787, 2.74696606, 0.        ])
193.84808349609375
11.540924948186671
Vd = array([-0.57016438, 32.73467425, -0.        ]) Va = array([  5.915609  , -20.67295911,   0.        ])
v_inf_d = array([-0.57016438,  2.95159037, -0.        ]) v_inf_a = array([0.14005348, 2.75599488, 0.        ])
194.40863037109375
11.612662987623692
Vd = array([-0.59099072, 32.73555609, -0.        ]) Va = array([  6.15168751, -20.60592938,   0.        ])
v_inf_d = array([-0.59099072,  2.9524722 , -0.        ]) v_inf_a = array([0.14719749, 2.76539977, 0.        ])
194.96575927734375
11.684305521064648
Vd = array([-0.61149561, 32.73649374, -0.        ]) Va = array([  6.38585477, -20.53666211,   0.        ])
v_inf_d = array([-0.61149561,  2.95340986, -0.        ]) v_inf_a = array([0.15439561, 2.77517702, 0.        ])
195.519287109375
11.755835406344051
Vd = array([-0.6316551 , 32.73748976, -0.        ]) Va = array([  6.61803748, -20.46522627,   0.        ])
v_inf_d = array([-0.6316551 ,  2.95440588, -0.        ]) v_inf_a = array([0.16165967, 2.78532452, 0.        ])
196.0693359375
11.827255746248383
Vd = array([-0.65149325, 32.73854426, -0.        ]) Va = array([  6.84825529, -20.39166019,   0.        ])
v_inf_d = array([-0.65149325,  2.95546038, -0.        ]) v_inf_a = array([0.16896935, 2.79583786, 0.        ])
196.61572265625
11.898549215093057
Vd = array([-0.67098609, 32.73965979, -0.        ]) Va = array([  7.07643731, -20.31603463,   0.        ])
v_inf_d = array([-0.67098609,  2.95657591, -0.        ]) v_inf_a = array([0.17633671, 2.80671474, 0.        ])
197.15850830078125
11.969714854742756
Vd = array([-0.69014786, 32.74083689, -0.        ]) Va = array([  7.30258698, -20.23839445,   0.        ])
v_inf_d = array([-0.69014786,  2.95775301, -0.        ]) v_inf_a = array([0.1837483 , 2.81795093, 0.        ])
197.6976318359375
12.040743469488318
Vd = array([-0.70897361, 32.74207707, -0.        ]) Va = array([  7.52667228, -20.15879811,   0.        ])
v_inf_d = array([-0.70897361,  2.95899319, -0.        ]) v_inf_a = array([0.1912037 , 2.82954301, 0.        ])
198.23309326171875
12.111630015556923
Vd = array([-0.7274678 , 32.74338129, -0.        ]) Va = array([  7.74868046, -20.07729715,   0.        ])
v_inf_d = array([-0.7274678 ,  2.96029741, -0.        ]) v_inf_a = array([0.19869632, 2.84148698, 0.        ])
198.7647705078125
12.182360988726098
Vd = array([-0.74561589, 32.7447516 , -0.        ]) Va = array([  7.96856369, -19.99395847,   0.        ])
v_inf_d = array([-0.74561589,  2.96166772, -0.        ]) v_inf_a = array([0.20623238, 2.85377969, 0.        ])
199.292724609375
12.252935542184806
Vd = array([-0.76343162, 32.74618835, -0.        ]) Va = array([  8.18632951, -19.90882646,   0.        ])
v_inf_d = array([-0.76343162,  2.96310447, -0.        ]) v_inf_a = array([0.21379938, 2.86641646, 0.        ])
199.81683349609375
12.323340065473134
Vd = array([-0.78090036, 32.74769358, -0.        ]) Va = array([  8.40193241, -19.82196899,   0.        ])
v_inf_d = array([-0.78090036,  2.9646097 , -0.        ]) v_inf_a = array([0.22140389, 2.87939396, 0.        ])
200.337158203125
12.39357377343572
Vd = array([-0.7980356 , 32.74926755, -0.        ]) Va = array([  8.61538192, -19.73343008,   0.        ])
v_inf_d = array([-0.7980356 ,  2.96618367, -0.        ]) v_inf_a = array([0.22903387, 2.89270731, 0.        ])
200.8536376953125
12.463627315241915
Vd = array([-0.81483192, 32.75091166, -0.        ]) Va = array([  8.82665265, -19.64326987,   0.        ])
v_inf_d = array([-0.81483192,  2.96782778, -0.        ]) v_inf_a = array([0.23669003, 2.9063525 , 0.        ])
201.36627197265625
12.533495664864647
Vd = array([-0.83129319, 32.75262669, -0.        ]) Va = array([  9.03573816, -19.55154014,   0.        ])
v_inf_d = array([-0.83129319,  2.96954281, -0.        ]) v_inf_a = array([0.24436706, 2.92032496, 0.        ])
201.875
12.6031694302524
Vd = array([-0.84741384, 32.754414  , -0.        ]) Va = array([  9.24261521, -19.45830139,   0.        ])

In [143]:
delta_vs_shaped = np.reshape(delta_vs, (-1, 3))
df = pd.DataFrame(delta_vs_shaped)
df.columns = ["LEO", "LMO", "TOTAL"]
with pd.ExcelWriter("deltaVs.xlsx") as writer:
    df.to_excel(writer, sheet_name="Sheet_name_1")

## Opt both

In [167]:
initial_guess = [170,200]

def wrapped_simulate(x):
    anomaly, t_of_f = x
    deltaV_LEO, deltaV_LMO, delta_total  = simulate(anomaly, t_of_f)
    return delta_total

optimized = minimize(wrapped_simulate,initial_guess, bounds=((1,360),(200,400)))
print(f"optimized angle = {optimized.x[0]} degrees    \noptimized time = {optimized.x[1]} days")

170.0
6.7945123689926135
Vd = array([-4.20335879, 32.97553758,  0.        ]) Va = array([ -8.87444277, -20.41519658,  -0.        ])
v_inf_d = array([-4.20335879,  3.19245369,  0.        ]) v_inf_a = array([-4.68425457,  3.34854154, -0.        ])
4.383080515774298 4.097125322710163 8.48020583848446
170.00000001
6.7945123693694836
Vd = array([-4.20335879, 32.97553758,  0.        ]) Va = array([ -8.87444276, -20.41519658,  -0.        ])
v_inf_d = array([-4.20335879,  3.19245369,  0.        ]) v_inf_a = array([-4.68425457,  3.34854154, -0.        ])
4.383080516387553 4.0971253233586316 8.480205839746183
170.0
6.7945123695105965
Vd = array([-4.20335879, 32.97553758,  0.        ]) Va = array([ -8.87444276, -20.41519658,  -0.        ])
v_inf_d = array([-4.20335879,  3.19245369,  0.        ]) v_inf_a = array([-4.68425457,  3.34854154, -0.        ])
4.383080515303426 4.097125321833279 8.480205837136705
169.87382778305158
6.796736890744781
Vd = array([-4.16210036, 32.97682543,  0.        ]) Va = array([ -8.89132472, -20.40147353,  -0.        ])
v_inf_d = array([-4.16210036,  3.19374155,  0.        ]) v_inf_a = array([-4.64881611,  3.35297968, -0.        ])
4.3690528797402415 4.077158834065228 8.44621171380547
169.8738277930516
6.7967368911211175
Vd = array([-4.16210036, 32.97682543,  0.        ]) Va = array([ -8.89132471, -20.40147353,  -0.        ])
v_inf_d = array([-4.16210036,  3.19374155,  0.        ]) v_inf_a = array([-4.64881611,  3.35297968, -0.        ])
4.369052880349161 4.077158834712518 8.44621171506168
169.87382778305158
6.7967368912620305
Vd = array([-4.16210036, 32.97682543,  0.        ]) Va = array([ -8.89132471, -20.40147353,  -0.        ])
v_inf_d = array([-4.16210036,  3.19374155,  0.        ]) v_inf_a = array([-4.6488161 ,  3.35297968, -0.        ])
4.369052879273655 4.077158833192221 8.446211712465875
141.47355191317595
6.922435046756583
Vd = array([ 4.27957638, 32.23553883,  0.        ]) Va = array([-12.86022844, -16.8089543 ,  -0.        ])
v_inf_d = array([4.27957638, 2.45245495, 0.        ]) v_inf_a = array([ 2.16997212,  2.0687044 , -0.        ])
4.23525817813602 2.2766828852015726 6.511941063337592
141.47355192317596
6.922435047016495
Vd = array([ 4.27957638, 32.23553883,  0.        ]) Va = array([-12.86022844, -16.8089543 ,  -0.        ])
v_inf_d = array([4.27957638, 2.45245495, 0.        ]) v_inf_a = array([ 2.16997212,  2.0687044 , -0.        ])
4.235258177437869 2.276682884949425 6.511941062387294
141.47355191317595
6.922435047158769
Vd = array([ 4.27957638, 32.23553883,  0.        ]) Va = array([-12.86022844, -16.8089543 ,  -0.        ])
v_inf_d = array([4.27957638, 2.45245495, 0.        ]) v_inf_a = array([ 2.16997212,  2.0687044 , -0.        ])
4.2352581784516055 2.2766828853457337 6.511941063797339
153.64993384930003
7.027583467136379
Vd = array([ 1.04846622, 32.76445903,  0.        ]) Va = array([-10.9680021 , -18.56862055,  -0.        ])
v_inf_d = array([1.04846622, 2.98137515, 0.        ]) v_inf_a = array([-0.2576483 ,  3.05454407, -0.        ])
3.614856684542607 2.3122178238097835 5.927074508352391
153.64993385930003
7.027583467448517
Vd = array([ 1.04846622, 32.76445903,  0.        ]) Va = array([-10.9680021 , -18.56862056,  -0.        ])
v_inf_d = array([1.04846622, 2.98137515, 0.        ]) v_inf_a = array([-0.25764831,  3.05454407, -0.        ])
3.614856684402781 2.312217824043505 5.927074508446286
153.64993384930003
7.027583467573199
Vd = array([ 1.04846622, 32.76445903,  0.        ]) Va = array([-10.9680021 , -18.56862055,  -0.        ])
v_inf_d = array([1.04846622, 2.98137515, 0.        ]) v_inf_a = array([-0.2576483 ,  3.05454407, -0.        ])
3.614856684602792 2.3122178235538797 5.927074508156672
152.63115456847993
7.0760004285071005
Vd = array([ 1.46086733, 32.71280323,  0.        ]) Va = array([-11.00470151, -18.48350225,  -0.        ])
v_inf_d = array([1.46086733, 2.92971934, 0.        ]) v_inf_a = array([ 0.08842158,  2.94581288, -0.        ])
3.6472385320446126 2.250197147664247 5.89743567970886
152.63115457847994
7.076000428817041
Vd = array([ 1.46086732, 32.71280323,  0.        ]) Va = array([-11.0047015 , -18.48350225,  -0.        ])
v_inf_d = array([1.46086732, 2.92971934, 0.        ]) v_inf_a = array([ 0.08842158,  2.94581288, -0.        ])
3.647238531834377 2.2501971478337035 5.897435679668081
152.63115456847993
7.076000428937631
Vd = array([ 1.46086733, 32.71280323,  0.        ]) Va = array([-11.00470151, -18.48350225,  -0.        ])
v_inf_d = array([1.46086733, 2.92971934, 0.        ]) v_inf_a = array([ 0.08842158,  2.94581288, -0.        ])
3.647238532141632 2.250197147471165 5.897435679612797
153.10184430107518
7.1764446997215225
Vd = array([ 1.57340784, 32.69316976,  0.        ]) Va = array([-10.70128572, -18.635534  ,  -0.        ])
v_inf_d = array([1.57340784, 2.91008588, 0.        ]) v_inf_a = array([ 0.21542137,  2.88418795, -0.        ])
3.657287952652794 2.2220014184103674 5.8792893710631615
153.10184431107518
7.176444700037607
Vd = array([ 1.57340783, 32.69316976,  0.        ]) Va = array([-10.70128572, -18.63553401,  -0.        ])
v_inf_d = array([1.57340783, 2.91008588, 0.        ]) v_inf_a = array([ 0.21542137,  2.88418795, -0.        ])
3.657287952423397 2.2220014185468706 5.879289370970268
153.10184430107518
7.17644470014821
Vd = array([ 1.57340784, 32.69316976,  0.        ]) Va = array([-10.70128572, -18.635534  ,  -0.        ])
v_inf_d = array([1.57340784, 2.91008588, 0.        ]) v_inf_a = array([ 0.21542137,  2.88418795, -0.        ])
3.6572879527596776 2.2220014182492784 5.879289371008956
157.289050781712
7.688551243641048
Vd = array([ 1.61108179, 32.66777211,  0.        ]) Va = array([ -8.87225987, -19.53314122,  -0.        ])
v_inf_d = array([1.61108179, 2.88468822, 0.        ]) v_inf_a = array([ 0.44403502,  2.7262293 , -0.        ])
3.656083266616246 2.15680253458207 5.812885801198316
157.28905079171201
7.68855124399544
Vd = array([ 1.61108179, 32.66777211,  0.        ]) Va = array([ -8.87225987, -19.53314123,  -0.        ])
v_inf_d = array([1.61108179, 2.88468822, 0.        ]) v_inf_a = array([ 0.44403502,  2.7262293 , -0.        ])
3.6560832663815965 2.156802534632477 5.812885801014073
157.289050781712
7.688551244054655
Vd = array([ 1.61108179, 32.66777211,  0.        ]) Va = array([ -8.87225987, -19.53314122,  -0.        ])
v_inf_d = array([1.61108179, 2.88468822, 0.        ]) v_inf_a = array([ 0.44403502,  2.7262293 , -0.        ])
3.6560832667260907 2.156802534505924 5.812885801232015
166.62263844666478
8.665265040435141
Vd = array([ 1.19904104, 32.68816341,  0.        ]) Va = array([ -5.07928268, -20.84793267,  -0.        ])
v_inf_d = array([1.19904104, 2.90507953, 0.        ]) v_inf_a = array([ 0.50359605,  2.62768003, -0.        ])
3.6099350504063157 2.1146302192477107 5.724565269654026
166.6226384566648
8.66526504086718
Vd = array([ 1.19904104, 32.68816341,  0.        ]) Va = array([ -5.07928267, -20.84793267,  -0.        ])
v_inf_d = array([1.19904104, 2.90507953, 0.        ]) v_inf_a = array([ 0.50359605,  2.62768003, -0.        ])
3.609935050238006 2.1146302192266297 5.724565269464636
166.62263844666478
8.665265040829915
Vd = array([ 1.19904104, 32.68816341,  0.        ]) Va = array([ -5.07928268, -20.84793267,  -0.        ])
v_inf_d = array([1.19904104, 2.90507953, 0.        ]) v_inf_a = array([ 0.50359606,  2.62768003, -0.        ])
3.6099350504847134 2.114630219248653 5.724565269733366
177.9006552941545
9.73693732566024
Vd = array([ 0.3186832 , 32.72402284,  0.        ]) Va = array([ -0.67428785, -21.47068345,  -0.        ])
v_inf_d = array([0.3186832 , 2.94093896, 0.        ]) v_inf_a = array([ 0.20966122,  2.64345266, -0.        ])
3.5597251267806893 2.103252493869938 5.6629776206506275
177.9006553041545
9.736937326181769
Vd = array([ 0.31868319, 32.72402284,  0.        ]) Va = array([ -0.67428785, -21.47068345,  -0.        ])
v_inf_d = array([0.31868319, 2.94093896, 0.        ]) v_inf_a = array([ 0.20966122,  2.64345266, -0.        ])
3.559725126738174 2.1032524938457247 5.662977620583899
177.9006552941545
9.736937326040467
Vd = array([ 0.3186832 , 32.72402284,  0.        ]) Va = array([ -0.67428785, -21.47068345,  -0.        ])
v_inf_d = array([0.3186832 , 2.94093896, 0.        ]) v_inf_a = array([ 0.20966122,  2.64345266, -0.        ])
3.5597251268013324 2.1032524938891255 5.662977620690458
180.10583815502625
9.918019454768592
Vd = array([ 0.07180408, 32.72645144, -0.        ]) Va = array([  0.12187203, -21.48237903,   0.        ])
v_inf_d = array([ 0.07180408,  2.94336755, -0.        ]) v_inf_a = array([0.07729792, 2.64791189, 0.        ])
3.556056445696372 2.1019570888202397 5.658013534516612
180.10583816502626
9.91801945530669
Vd = array([ 0.07180408, 32.72645144, -0.        ]) Va = array([  0.12187203, -21.48237903,   0.        ])
v_inf_d = array([ 0.07180408,  2.94336755, -0.        ]) v_inf_a = array([0.07729792, 2.64791189, 0.        ])
3.5560564459470303 2.1019570884979553 5.658013534444986
180.10583815502625
9.918019455147776
Vd = array([ 0.07180408, 32.72645144, -0.        ]) Va = array([  0.12187203, -21.48237903,   0.        ])
v_inf_d = array([ 0.07180408,  2.94336755, -0.        ]) v_inf_a = array([0.07729792, 2.64791189, 0.        ])
3.5560564457016373 2.1019570888319645 5.658013534533602
188.92656959851328
10.677857928806313
Vd = array([-0.8781351 , 32.70570036, -0.        ]) Va = array([  3.33028877, -21.20907392,   0.        ])
v_inf_d = array([-0.8781351 ,  2.92261648, -0.        ]) v_inf_a = array([-0.41397899,  2.62899198,  0.        ])
3.5848080207658732 2.1078579202182564 5.69266594098413
188.9265696085133
10.677857929413165
Vd = array([-0.8781351 , 32.70570036, -0.        ]) Va = array([  3.33028877, -21.20907392,   0.        ])
v_inf_d = array([-0.8781351 ,  2.92261648, -0.        ]) v_inf_a = array([-0.41397899,  2.62899198,  0.        ])
3.584808020873158 2.10785792024254 5.692665941115698
188.92656959851328
10.677857929180577
Vd = array([-0.8781351 , 32.70570036, -0.        ]) Va = array([  3.33028877, -21.20907392,   0.        ])
v_inf_d = array([-0.8781351 ,  2.92261648, -0.        ]) v_inf_a = array([-0.41397898,  2.62899198,  0.        ])
3.584808020715803 2.1078579202068797 5.692665940922683
182.04567949398145
10.080229427678002
Vd = array([-0.14216705, 32.72595801, -0.        ]) Va = array([  0.82537455, -21.46646172,   0.        ])
v_inf_d = array([-0.14216705,  2.94287413, -0.        ]) v_inf_a = array([-0.035988  ,  2.64849176,  0.        ])
3.5565994232656752 2.101812239365729 5.658411662631404
182.04567950398146
10.080229428231146
Vd = array([-0.14216705, 32.72595801, -0.        ]) Va = array([  0.82537455, -21.46646172,   0.        ])
v_inf_d = array([-0.14216705,  2.94287413, -0.        ]) v_inf_a = array([-0.035988  ,  2.64849176,  0.        ])
3.556599423282952 2.101812239363295 5.658411662646247
182.04567949398145
10.080229428056212
Vd = array([-0.14216705, 32.72595801, -0.        ]) Va = array([  0.82537455, -21.46646172,   0.        ])
v_inf_d = array([-0.14216705,  2.94287413, -0.        ]) v_inf_a = array([-0.03598799,  2.64849176,  0.        ])
3.5565994232578824 2.101812239371397 5.6584116626292795
180.30891754827513
9.906804777483957
Vd = array([-9.80545266e-03,  3.27264172e+01, -0.00000000e+00]) Va = array([  0.13633105, -21.48212224,   0.        ])
v_inf_d = array([-0.00980545,  2.94333333, -0.        ]) v_inf_a = array([0.0062299 , 2.64785912, 0.        ])
3.555821343432509 2.1013973640175667 5.657218707450076
180.30891755827514
9.906804778022964
Vd = array([-9.80545438e-03,  3.27264172e+01, -0.00000000e+00]) Va = array([  0.13633105, -21.48212224,   0.        ])
v_inf_d = array([-0.00980545,  2.94333333, -0.        ]) v_inf_a = array([0.0062299 , 2.64785912, 0.        ])
3.5558213434626396 2.1013973639807775 5.657218707443417
180.30891754827513
9.906804777864501
Vd = array([-9.80545186e-03,  3.27264172e+01, -0.00000000e+00]) Va = array([  0.13633105, -21.48212224,   0.        ])
v_inf_d = array([-0.00980545,  2.94333333, -0.        ]) v_inf_a = array([0.0062299 , 2.64785912, 0.        ])
3.55582134343215 2.1013973640201202 5.65721870745227
180.72358394349638
9.945934086706274
Vd = array([-0.04590479, 32.72636884, -0.        ]) Va = array([  0.29638682, -21.48048328,   0.        ])
v_inf_d = array([-0.04590479,  2.94328496, -0.        ]) v_inf_a = array([-0.00834517,  2.64792457,  0.        ])
3.5558984886346963 2.1014313526642425 5.657329841298939
180.7235839534964
9.945934087248611
Vd = array([-0.04590479, 32.72636884, -0.        ]) Va = array([  0.29638682, -21.48048328,   0.        ])
v_inf_d = array([-0.04590479,  2.94328496, -0.        ]) v_inf_a = array([-0.00834517,  2.64792457,  0.        ])
3.555898488645507 2.1014313526564354 5.657329841301943
180.72358394349638
9.945934087086371
Vd = array([-0.04590479, 32.72636884, -0.        ]) Va = array([  0.29638682, -21.48048328,   0.        ])
v_inf_d = array([-0.04590479,  2.94328496, -0.        ]) v_inf_a = array([-0.00834517,  2.64792457,  0.        ])
3.5558984886322182 2.1014313526669 5.657329841299118
180.38565082176282
9.914036749027366
Vd = array([-1.64918899e-02,  3.27264134e+01, -0.00000000e+00]) Va = array([  0.16594357, -21.48191224,   0.        ])
v_inf_d = array([-0.01649189,  2.94332955, -0.        ]) v_inf_a = array([0.00352651, 2.64787324, 0.        ])
3.555828208362785 2.1014017220355017 5.6572299303982865
180.38565083176283
9.914036749566975
Vd = array([-1.64918916e-02,  3.27264134e+01, -0.00000000e+00]) Va = array([  0.16594358, -21.48191224,   0.        ])
v_inf_d = array([-0.01649189,  2.94332955, -0.        ]) v_inf_a = array([0.00352651, 2.64787324, 0.        ])
3.555828208390821 2.1014017220023096 5.657229930393131
180.38565082176282
9.914036749407835
Vd = array([-1.64918891e-02,  3.27264134e+01, -0.00000000e+00]) Va = array([  0.16594358, -21.48191224,   0.        ])
v_inf_d = array([-0.01649189,  2.94332955, -0.        ]) v_inf_a = array([0.00352651, 2.64787324, 0.        ])
3.5558282083620316 2.1014017220380747 5.657229930400106
180.32095194344126
9.907938732051637
Vd = array([-1.08543045e-02,  3.27264168e+01, -0.00000000e+00]) Va = array([  0.14097513, -21.4820921 ,   0.        ])
v_inf_d = array([-0.0108543 ,  2.94333289, -0.        ]) v_inf_a = array([0.00580573, 2.6478614 , 0.        ])
3.555822197106295 2.101397989505217 5.657220186611512
180.32095195344127
9.907938732590852
Vd = array([-1.08543062e-02,  3.27264168e+01, -0.00000000e+00]) Va = array([  0.14097513, -21.4820921 ,   0.        ])
v_inf_d = array([-0.01085431,  2.94333289, -0.        ]) v_inf_a = array([0.00580572, 2.6478614 , 0.        ])
3.5558221970788217 2.1013979895371495 5.657220186615971
180.32095194344126
9.90793873243217
Vd = array([-1.08543037e-02,  3.27264168e+01, -0.00000000e+00]) Va = array([  0.14097513, -21.4820921 ,   0.        ])
v_inf_d = array([-0.0108543 ,  2.94333289, -0.        ]) v_inf_a = array([0.00580573, 2.6478614 , 0.        ])
3.555822197105874 2.1013979895077792 5.657220186613653
180.3135828736096
9.907244361354223
Vd = array([-1.02120652e-02,  3.27264170e+01, -0.00000000e+00]) Va = array([  0.13813139, -21.48211068,   0.        ])
v_inf_d = array([-0.01021207,  2.94333317, -0.        ]) v_inf_a = array([0.00606545, 2.64786001, 0.        ])
3.5558216645344043 2.1013976039239477 5.657219268458352
180.3135828836096
9.907244361893328
Vd = array([-1.02120669e-02,  3.27264170e+01, -0.00000000e+00]) Va = array([  0.1381314 , -21.48211068,   0.        ])
v_inf_d = array([-0.01021207,  2.94333317, -0.        ]) v_inf_a = array([0.00606545, 2.64786001, 0.        ])
3.5558216645327185 2.1013976039250863 5.657219268457805
180.3135828736096
9.907244361734765
Vd = array([-1.02120644e-02,  3.27264170e+01, -0.00000000e+00]) Va = array([  0.1381314 , -21.48211068,   0.        ])
v_inf_d = array([-0.01021206,  2.94333317, -0.        ]) v_inf_a = array([0.00606545, 2.64786001, 0.        ])
3.555821664534024 2.1013976039264977 5.657219268460522
180.31008632589865
9.906914902557341
Vd = array([-9.90732001e-03,  3.27264172e+01, -0.00000000e+00]) Va = array([  0.13678208, -21.48211935,   0.        ])
v_inf_d = array([-0.00990732,  2.94333329, -0.        ]) v_inf_a = array([0.0061887 , 2.64785935, 0.        ])
3.5558214227313467 2.101397423784773 5.65721884651612
180.31008633589866
9.906914903096483
Vd = array([-9.90732173e-03,  3.27264172e+01, -0.00000000e+00]) Va = array([  0.13678208, -21.48211935,   0.        ])
v_inf_d = array([-0.00990732,  2.94333329, -0.        ]) v_inf_a = array([0.0061887 , 2.64785935, 0.        ])
3.5558214226985108 2.1013974238229327 5.6572188465214435
180.31008632589865
9.906914902937887
Vd = array([-9.90731921e-03,  3.27264172e+01, -0.00000000e+00]) Va = array([  0.13678208, -21.48211935,   0.        ])
v_inf_d = array([-0.00990732,  2.94333329, -0.        ]) v_inf_a = array([0.0061887 , 2.64785935, 0.        ])
3.5558214227309826 2.101397423787322 5.657218846518305
180.30939130202827
9.906849415603865
Vd = array([-9.84674377e-03,  3.27264172e+01, -0.00000000e+00]) Va = array([  0.13651387, -21.48212107,   0.        ])
v_inf_d = array([-0.00984674,  2.94333331, -0.        ]) v_inf_a = array([0.0062132 , 2.64785921, 0.        ])
3.555821375481104 2.1013973882193344 5.657218763700438
180.30939131202828
9.906849416142936
Vd = array([-9.84674549e-03,  3.27264172e+01, -0.00000000e+00]) Va = array([  0.13651387, -21.48212107,   0.        ])
v_inf_d = array([-0.00984675,  2.94333331, -0.        ]) v_inf_a = array([0.0062132 , 2.64785921, 0.        ])
3.555821375477917 2.1013973882221952 5.657218763700112
180.30939130202827
9.906849415984412
Vd = array([-9.84674297e-03,  3.27264172e+01, -0.00000000e+00]) Va = array([  0.13651387, -21.48212107,   0.        ])
v_inf_d = array([-0.00984674,  2.94333331, -0.        ]) v_inf_a = array([0.0062132 , 2.64785921, 0.        ])
3.5558213754807433 2.101397388221886 5.657218763702629
180.30903956341203
9.906816274003733
Vd = array([-9.81608718e-03,  3.27264172e+01, -0.00000000e+00]) Va = array([  0.13637814, -21.48212194,   0.        ])
v_inf_d = array([-0.00981609,  2.94333332, -0.        ]) v_inf_a = array([0.0062256 , 2.64785915, 0.        ])
3.5558213516632406 2.1013973702607167 5.657218721923957
180.30903957341204
9.906816274542782
Vd = array([-9.81608890e-03,  3.27264172e+01, -0.00000000e+00]) Va = array([  0.13637814, -21.48212194,   0.        ])
v_inf_d = array([-0.00981609,  2.94333332, -0.        ]) v_inf_a = array([0.0062256 , 2.64785915, 0.        ])
3.5558213516720922 2.101397370249245 5.657218721921337
180.30903956341203
9.906816274384282
Vd = array([-9.81608638e-03,  3.27264172e+01, -0.00000000e+00]) Va = array([  0.13637814, -21.48212194,   0.        ])
v_inf_d = array([-0.00981609,  2.94333332, -0.        ]) v_inf_a = array([0.0062256 , 2.64785915, 0.        ])
3.5558213516628783 2.101397370263274 5.657218721926152
180.3089431793058
9.906807192492005
Vd = array([-9.80768659e-03,  3.27264172e+01, -0.00000000e+00]) Va = array([  0.13634094, -21.48212217,   0.        ])
v_inf_d = array([-0.00980769,  2.94333333, -0.        ]) v_inf_a = array([0.00622899, 2.64785913, 0.        ])
3.5558213452056755 2.10139736527542 5.657218710481096
180.3089431893058
9.906807193031094
Vd = array([-9.80768831e-03,  3.27264172e+01, -0.00000000e+00]) Va = array([  0.13634094, -21.48212217,   0.        ])
v_inf_d = array([-0.00980769,  2.94333333, -0.        ]) v_inf_a = array([0.00622899, 2.64785913, 0.        ])
3.555821345193257 2.1013973652892677 5.657218710482525
180.3089431793058
9.906807192872549
Vd = array([-9.80768579e-03,  3.27264172e+01, -0.00000000e+00]) Va = array([  0.13634094, -21.48212217,   0.        ])
v_inf_d = array([-0.00980769,  2.94333333, -0.        ]) v_inf_a = array([0.006229  , 2.64785913, 0.        ])
3.555821345205313 2.1013973652779727 5.657218710483286
180.30892534965574
9.90680551254589
Vd = array([-9.80613261e-03,  3.27264172e+01, -0.00000000e+00]) Va = array([  0.13633406, -21.48212222,   0.        ])

In [168]:
simulate(optimized.x[0], optimized.x[1])

180.30891755341997
9.906804777968665
Vd = array([-9.80545310e-03,  3.27264172e+01, -0.00000000e+00]) Va = array([  0.13633105, -21.48212224,   0.        ])
v_inf_d = array([-0.00980545,  2.94333333, -0.        ]) v_inf_a = array([0.0062299 , 2.64785912, 0.        ])
3.5558213434555483 2.101397363990827 5.657218707446376

(np.float64(3.5558213434555483),
 np.float64(2.101397363990827),
 np.float64(5.657218707446376))